(* Generated by the OCaml generator. Do not edit. *)
open! Melange_json.Primitives

module AddReactionDataAddReactionToPostAddReactionToPostPayload = struct
  type t = {
    __typename : string;
    clientMutationId : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let addReactionDataAddReactionToPostAddReactionToPostPayload_of_json = AddReactionDataAddReactionToPostAddReactionToPostPayload.of_json
let addReactionDataAddReactionToPostAddReactionToPostPayload_to_json = AddReactionDataAddReactionToPostAddReactionToPostPayload.to_json

module AddReactionDataAddReactionToPostInvalidInputError = struct
  type t = {
    __typename : string;
    inputPath : string;
  } [@@deriving json]
end
let addReactionDataAddReactionToPostInvalidInputError_of_json = AddReactionDataAddReactionToPostInvalidInputError.of_json
let addReactionDataAddReactionToPostInvalidInputError_to_json = AddReactionDataAddReactionToPostInvalidInputError.to_json

module AddReactionDataAddReactionToPostNotAuthenticatedError = struct
  type t = {
    __typename : string;
    notAuthenticated : string;
  } [@@deriving json]
end
let addReactionDataAddReactionToPostNotAuthenticatedError_of_json = AddReactionDataAddReactionToPostNotAuthenticatedError.of_json
let addReactionDataAddReactionToPostNotAuthenticatedError_to_json = AddReactionDataAddReactionToPostNotAuthenticatedError.to_json

module AddReactionDataAddReactionToPost = struct
  type t = Melange_json.t
  let of_json (j : Melange_json.t) : t = j
  let to_json (x : t) : Melange_json.t = x
end
let addReactionDataAddReactionToPost_of_json = AddReactionDataAddReactionToPost.of_json
let addReactionDataAddReactionToPost_to_json = AddReactionDataAddReactionToPost.to_json

module AddReactionData = struct
  type t = {
    addReactionToPost : AddReactionDataAddReactionToPost.t;
  } [@@deriving json]
end
let addReactionData_of_json = AddReactionData.of_json
let addReactionData_to_json = AddReactionData.to_json

module AddReactionResponse = struct
  type t = {
    data : AddReactionData.t;
  } [@@deriving json]
end
let addReactionResponse_of_json = AddReactionResponse.of_json
let addReactionResponse_to_json = AddReactionResponse.to_json

