(* Generated by the OCaml generator. Do not edit. *)
open! Melange_json.Primitives
open ComponentSchemas

module AddReaction = struct
  type request = {
    input : Melange_json.t;
  } [@@deriving json]
end
let addReaction_send (fetch : string -> string -> Js.Json.t -> Js.Json.t Js.Promise.t) (req : AddReaction.request) =
  let variables = AddReaction.request_to_json req in
  let body = Js.Json.object_ (Js.Dict.fromList [("query", Js.Json.string "mutation AddReaction($input: AddReactionToPostInput!) {\n  addReactionToPost(input: $input) {\n    __typename\n    ... on AddReactionToPostPayload { clientMutationId }\n    ... on InvalidInputError { inputPath }\n    ... on NotAuthenticatedError { notAuthenticated }\n  }\n}"); ("variables", variables)]) in
  Js.Promise.then_ (fun j -> Js.Promise.resolve (AddReactionResponse.of_json j)) (fetch "POST" "/graphql" body)

