// API endpoints (ReScript type layer).
// Generated by melange-jsdoc-gen. DO NOT EDIT.
// send delegates encode/decode to the Melange layer; inject fetch for transport.

type fetchFn = (string, string, JSON.t) => promise<JSON.t>

module AppBskyActor = {
  module AppBskyActorGetPreferences = {
    type request = unit
    type response = ComponentSchemas.AppBskyActorGetPreferencesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyActorGetPreferences_send"
  }

  module AppBskyActorGetProfile = {
    type request = {
      actor: string,
    }
    type response = ComponentSchemas.AppBskyActorDefsProfileViewDetailed.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyActorGetProfile_send"
  }

  module AppBskyActorGetProfiles = {
    type request = {
      actors: array<string>,
    }
    type response = ComponentSchemas.AppBskyActorGetProfilesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyActorGetProfiles_send"
  }

  module AppBskyActorGetSuggestions = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyActorGetSuggestionsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyActorGetSuggestions_send"
  }

  module AppBskyActorPutPreferences = {
    type request = {
      preferences: ComponentSchemas.AppBskyActorDefsPreferences.t,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyActorPutPreferences_send"
  }

  module AppBskyActorSearchActors = {
    type request = {
      q?: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyActorSearchActorsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyActorSearchActors_send"
  }

  module AppBskyActorSearchActorsTypeahead = {
    type request = {
      q?: string,
      limit?: int,
    }
    type response = ComponentSchemas.AppBskyActorSearchActorsTypeaheadResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyActorSearchActorsTypeahead_send"
  }

}

module AppBskyAgeassurance = {
  module AppBskyAgeassuranceBegin = {
    type request = {
      email: string,
      language: string,
      regionCode?: string,
      countryCode: string,
    }
    type response = ComponentSchemas.AppBskyAgeassuranceDefsState.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyAgeassuranceBegin_send"
  }

  module AppBskyAgeassuranceGetConfig = {
    type request = unit
    type response = ComponentSchemas.AppBskyAgeassuranceDefsConfig.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyAgeassuranceGetConfig_send"
  }

  module AppBskyAgeassuranceGetState = {
    type request = {
      regionCode?: string,
      countryCode: string,
    }
    type response = ComponentSchemas.AppBskyAgeassuranceGetStateResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyAgeassuranceGetState_send"
  }

}

module AppBskyBookmark = {
  module AppBskyBookmarkCreateBookmark = {
    type request = {
      cid: string,
      uri: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyBookmarkCreateBookmark_send"
  }

  module AppBskyBookmarkDeleteBookmark = {
    type request = {
      uri: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyBookmarkDeleteBookmark_send"
  }

  module AppBskyBookmarkGetBookmarks = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyBookmarkGetBookmarksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyBookmarkGetBookmarks_send"
  }

}

module AppBskyContact = {
  module AppBskyContactDismissMatch = {
    type request = {
      subject: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactDismissMatch_send"
  }

  module AppBskyContactGetMatches = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyContactGetMatchesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactGetMatches_send"
  }

  module AppBskyContactGetSyncStatus = {
    type request = unit
    type response = ComponentSchemas.AppBskyContactGetSyncStatusResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactGetSyncStatus_send"
  }

  module AppBskyContactImportContacts = {
    type request = {
      token: string,
      contacts: array<string>,
    }
    type response = ComponentSchemas.AppBskyContactImportContactsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactImportContacts_send"
  }

  module AppBskyContactRemoveData = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactRemoveData_send"
  }

  module AppBskyContactSendNotification = {
    type request = {
      to: string,
      from: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactSendNotification_send"
  }

  module AppBskyContactStartPhoneVerification = {
    type request = {
      phone: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactStartPhoneVerification_send"
  }

  module AppBskyContactVerifyPhone = {
    type request = {
      code: string,
      phone: string,
    }
    type response = ComponentSchemas.AppBskyContactVerifyPhoneResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyContactVerifyPhone_send"
  }

}

module AppBskyDraft = {
  module AppBskyDraftCreateDraft = {
    type request = {
      draft: ComponentSchemas.AppBskyDraftDefsDraft.t,
    }
    type response = ComponentSchemas.AppBskyDraftCreateDraftResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyDraftCreateDraft_send"
  }

  module AppBskyDraftDeleteDraft = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyDraftDeleteDraft_send"
  }

  module AppBskyDraftGetDrafts = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyDraftGetDraftsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyDraftGetDrafts_send"
  }

  module AppBskyDraftUpdateDraft = {
    type request = {
      draft: ComponentSchemas.AppBskyDraftDefsDraftWithId.t,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyDraftUpdateDraft_send"
  }

}

module AppBskyFeed = {
  module AppBskyFeedDescribeFeedGenerator = {
    type request = unit
    type response = ComponentSchemas.AppBskyFeedDescribeFeedGeneratorResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedDescribeFeedGenerator_send"
  }

  module AppBskyFeedGetActorFeeds = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetActorFeedsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetActorFeeds_send"
  }

  module AppBskyFeedGetActorLikes = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetActorLikesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetActorLikes_send"
  }

  module AppBskyFeedGetAuthorFeed = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
      filter?: string,
      includePins?: bool,
    }
    type response = ComponentSchemas.AppBskyFeedGetActorLikesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetAuthorFeed_send"
  }

  module AppBskyFeedGetFeed = {
    type request = {
      feed: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetActorLikesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetFeed_send"
  }

  module AppBskyFeedGetFeedGenerator = {
    type request = {
      feed: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetFeedGeneratorResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetFeedGenerator_send"
  }

  module AppBskyFeedGetFeedGenerators = {
    type request = {
      feeds: array<string>,
    }
    type response = ComponentSchemas.AppBskyFeedGetFeedGeneratorsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetFeedGenerators_send"
  }

  module AppBskyFeedGetFeedSkeleton = {
    type request = {
      feed: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetFeedSkeletonResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetFeedSkeleton_send"
  }

  module AppBskyFeedGetLikes = {
    type request = {
      cid?: string,
      uri: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetLikesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetLikes_send"
  }

  module AppBskyFeedGetListFeed = {
    type request = {
      list: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetActorLikesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetListFeed_send"
  }

  module AppBskyFeedGetPostThread = {
    type request = {
      uri: string,
      depth?: int,
      parentHeight?: int,
    }
    type response = ComponentSchemas.AppBskyFeedGetPostThreadResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetPostThread_send"
  }

  module AppBskyFeedGetPosts = {
    type request = {
      uris: array<string>,
    }
    type response = ComponentSchemas.AppBskyFeedGetPostsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetPosts_send"
  }

  module AppBskyFeedGetQuotes = {
    type request = {
      cid?: string,
      uri: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetQuotesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetQuotes_send"
  }

  module AppBskyFeedGetRepostedBy = {
    type request = {
      cid?: string,
      uri: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetRepostedByResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetRepostedBy_send"
  }

  module AppBskyFeedGetSuggestedFeeds = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetActorFeedsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetSuggestedFeeds_send"
  }

  module AppBskyFeedGetTimeline = {
    type request = {
      limit?: int,
      cursor?: string,
      algorithm?: string,
    }
    type response = ComponentSchemas.AppBskyFeedGetActorLikesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedGetTimeline_send"
  }

  module AppBskyFeedSearchPosts = {
    type request = {
      q: string,
      tag?: array<string>,
      url?: string,
      lang?: string,
      sort?: string,
      limit?: int,
      since?: string,
      until?: string,
      author?: string,
      cursor?: string,
      domain?: string,
      mentions?: string,
    }
    type response = ComponentSchemas.AppBskyFeedSearchPostsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedSearchPosts_send"
  }

  module AppBskyFeedSendInteractions = {
    type request = {
      feed?: string,
      interactions: array<ComponentSchemas.AppBskyFeedDefsInteraction.t>,
    }
    type response = ComponentSchemas.AppBskyFeedSendInteractionsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyFeedSendInteractions_send"
  }

}

module AppBskyGraph = {
  module AppBskyGraphGetActorStarterPacks = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetActorStarterPacksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetActorStarterPacks_send"
  }

  module AppBskyGraphGetBlocks = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetBlocksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetBlocks_send"
  }

  module AppBskyGraphGetFollowers = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetFollowersResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetFollowers_send"
  }

  module AppBskyGraphGetFollows = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetFollowsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetFollows_send"
  }

  module AppBskyGraphGetKnownFollowers = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetFollowersResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetKnownFollowers_send"
  }

  module AppBskyGraphGetList = {
    type request = {
      list: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetListResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetList_send"
  }

  module AppBskyGraphGetListBlocks = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetListBlocksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetListBlocks_send"
  }

  module AppBskyGraphGetListMutes = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetListBlocksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetListMutes_send"
  }

  module AppBskyGraphGetLists = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
      purposes?: array<string>,
    }
    type response = ComponentSchemas.AppBskyGraphGetListBlocksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetLists_send"
  }

  module AppBskyGraphGetListsWithMembership = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
      purposes?: array<string>,
    }
    type response = ComponentSchemas.AppBskyGraphGetListsWithMembershipResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetListsWithMembership_send"
  }

  module AppBskyGraphGetMutes = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetMutesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetMutes_send"
  }

  module AppBskyGraphGetRelationships = {
    type request = {
      actor: string,
      others?: array<string>,
    }
    type response = ComponentSchemas.AppBskyGraphGetRelationshipsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetRelationships_send"
  }

  module AppBskyGraphGetStarterPack = {
    type request = {
      starterPack: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetStarterPackResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetStarterPack_send"
  }

  module AppBskyGraphGetStarterPacks = {
    type request = {
      uris: array<string>,
    }
    type response = ComponentSchemas.AppBskyGraphGetStarterPacksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetStarterPacks_send"
  }

  module AppBskyGraphGetStarterPacksWithMembership = {
    type request = {
      actor: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetStarterPacksWithMembershipResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetStarterPacksWithMembership_send"
  }

  module AppBskyGraphGetSuggestedFollowsByActor = {
    type request = {
      actor: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetSuggestedFollowsByActorResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphGetSuggestedFollowsByActor_send"
  }

  module AppBskyGraphMuteActor = {
    type request = {
      actor: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphMuteActor_send"
  }

  module AppBskyGraphMuteActorList = {
    type request = {
      list: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphMuteActorList_send"
  }

  module AppBskyGraphMuteThread = {
    type request = {
      root: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphMuteThread_send"
  }

  module AppBskyGraphSearchStarterPacks = {
    type request = {
      q: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyGraphGetActorStarterPacksResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphSearchStarterPacks_send"
  }

  module AppBskyGraphUnmuteActor = {
    type request = {
      actor: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphUnmuteActor_send"
  }

  module AppBskyGraphUnmuteActorList = {
    type request = {
      list: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphUnmuteActorList_send"
  }

  module AppBskyGraphUnmuteThread = {
    type request = {
      root: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyGraphUnmuteThread_send"
  }

}

module AppBskyLabeler = {
  module AppBskyLabelerGetServices = {
    type request = {
      dids: array<string>,
      detailed?: bool,
    }
    type response = ComponentSchemas.AppBskyLabelerGetServicesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyLabelerGetServices_send"
  }

}

module AppBskyNotification = {
  module AppBskyNotificationGetPreferences = {
    type request = unit
    type response = ComponentSchemas.AppBskyNotificationGetPreferencesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationGetPreferences_send"
  }

  module AppBskyNotificationGetUnreadCount = {
    type request = {
      seenAt?: string,
      priority?: bool,
    }
    type response = ComponentSchemas.AppBskyNotificationGetUnreadCountResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationGetUnreadCount_send"
  }

  module AppBskyNotificationListActivitySubscriptions = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.AppBskyNotificationListActivitySubscriptionsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationListActivitySubscriptions_send"
  }

  module AppBskyNotificationListNotifications = {
    type request = {
      limit?: int,
      cursor?: string,
      seenAt?: string,
      reasons?: array<string>,
      priority?: bool,
    }
    type response = ComponentSchemas.AppBskyNotificationListNotificationsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationListNotifications_send"
  }

  module AppBskyNotificationPutActivitySubscription = {
    type request = {
      subject: string,
      activitySubscription: ComponentSchemas.AppBskyNotificationDefsActivitySubscription.t,
    }
    type response = ComponentSchemas.AppBskyNotificationPutActivitySubscriptionResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationPutActivitySubscription_send"
  }

  module AppBskyNotificationPutPreferences = {
    type request = {
      priority: bool,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationPutPreferences_send"
  }

  module AppBskyNotificationPutPreferencesV2 = {
    type request = {
      chat?: ComponentSchemas.AppBskyNotificationDefsChatPreference.t,
      like?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      quote?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      reply?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      follow?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      repost?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      mention?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      verified?: ComponentSchemas.AppBskyNotificationDefsPreference.t,
      unverified?: ComponentSchemas.AppBskyNotificationDefsPreference.t,
      likeViaRepost?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      subscribedPost?: ComponentSchemas.AppBskyNotificationDefsPreference.t,
      repostViaRepost?: ComponentSchemas.AppBskyNotificationDefsFilterablePreference.t,
      starterpackJoined?: ComponentSchemas.AppBskyNotificationDefsPreference.t,
    }
    type response = ComponentSchemas.AppBskyNotificationGetPreferencesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationPutPreferencesV2_send"
  }

  module AppBskyNotificationRegisterPush = {
    type request = {
      appId: string,
      token: string,
      platform: string,
      serviceDid: string,
      ageRestricted?: bool,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationRegisterPush_send"
  }

  module AppBskyNotificationUnregisterPush = {
    type request = {
      appId: string,
      token: string,
      platform: string,
      serviceDid: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationUnregisterPush_send"
  }

  module AppBskyNotificationUpdateSeen = {
    type request = {
      seenAt: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyNotificationUpdateSeen_send"
  }

}

module AppBskyVideo = {
  module AppBskyVideoGetJobStatus = {
    type request = {
      jobId: string,
    }
    type response = ComponentSchemas.AppBskyVideoGetJobStatusResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyVideoGetJobStatus_send"
  }

  module AppBskyVideoGetUploadLimits = {
    type request = unit
    type response = ComponentSchemas.AppBskyVideoGetUploadLimitsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyVideoGetUploadLimits_send"
  }

  module AppBskyVideoUploadVideo = {
    type request = unit
    type response = ComponentSchemas.AppBskyVideoGetJobStatusResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "appBskyVideoUploadVideo_send"
  }

}

module ComAtprotoAdmin = {
  module ComAtprotoAdminDeleteAccount = {
    type request = {
      did: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminDeleteAccount_send"
  }

  module ComAtprotoAdminDisableAccountInvites = {
    type request = {
      note?: string,
      account: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminDisableAccountInvites_send"
  }

  module ComAtprotoAdminDisableInviteCodes = {
    type request = {
      codes?: array<string>,
      accounts?: array<string>,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminDisableInviteCodes_send"
  }

  module ComAtprotoAdminEnableAccountInvites = {
    type request = {
      note?: string,
      account: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminEnableAccountInvites_send"
  }

  module ComAtprotoAdminGetAccountInfo = {
    type request = {
      did: string,
    }
    type response = ComponentSchemas.ComAtprotoAdminDefsAccountView.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminGetAccountInfo_send"
  }

  module ComAtprotoAdminGetAccountInfos = {
    type request = {
      dids: array<string>,
    }
    type response = ComponentSchemas.ComAtprotoAdminGetAccountInfosResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminGetAccountInfos_send"
  }

  module ComAtprotoAdminGetInviteCodes = {
    type request = {
      sort?: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.ComAtprotoAdminGetInviteCodesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminGetInviteCodes_send"
  }

  module ComAtprotoAdminGetSubjectStatus = {
    type request = {
      did?: string,
      uri?: string,
      blob?: string,
    }
    type response = ComponentSchemas.ComAtprotoAdminGetSubjectStatusResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminGetSubjectStatus_send"
  }

  module ComAtprotoAdminSearchAccounts = {
    type request = {
      email?: string,
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.ComAtprotoAdminSearchAccountsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminSearchAccounts_send"
  }

  module ComAtprotoAdminSendEmail = {
    type request = {
      comment?: string,
      content: string,
      subject?: string,
      senderDid: string,
      recipientDid: string,
    }
    type response = ComponentSchemas.ComAtprotoAdminSendEmailResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminSendEmail_send"
  }

  module ComAtprotoAdminUpdateAccountEmail = {
    type request = {
      email: string,
      account: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminUpdateAccountEmail_send"
  }

  module ComAtprotoAdminUpdateAccountHandle = {
    type request = {
      did: string,
      handle: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminUpdateAccountHandle_send"
  }

  module ComAtprotoAdminUpdateAccountPassword = {
    type request = {
      did: string,
      password: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminUpdateAccountPassword_send"
  }

  module ComAtprotoAdminUpdateAccountSigningKey = {
    type request = {
      did: string,
      signingKey: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminUpdateAccountSigningKey_send"
  }

  module ComAtprotoAdminUpdateSubjectStatus = {
    type request = {
      subject: JSON.t,
      takedown?: ComponentSchemas.ComAtprotoAdminDefsStatusAttr.t,
      deactivated?: ComponentSchemas.ComAtprotoAdminDefsStatusAttr.t,
    }
    type response = ComponentSchemas.ComAtprotoAdminUpdateSubjectStatusResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoAdminUpdateSubjectStatus_send"
  }

}

module ComAtprotoIdentity = {
  module ComAtprotoIdentityGetRecommendedDidCredentials = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoIdentityGetRecommendedDidCredentialsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoIdentityGetRecommendedDidCredentials_send"
  }

  module ComAtprotoIdentityRefreshIdentity = {
    type request = {
      identifier: string,
    }
    type response = ComponentSchemas.ComAtprotoIdentityDefsIdentityInfo.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoIdentityRefreshIdentity_send"
  }

  module ComAtprotoIdentityRequestPlcOperationSignature = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoIdentityRequestPlcOperationSignature_send"
  }

  module ComAtprotoIdentityResolveHandle = {
    type request = {
      handle: string,
    }
    type response = ComponentSchemas.AppBskyActorDefsLabelerPrefItem.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoIdentityResolveHandle_send"
  }

  module ComAtprotoIdentitySignPlcOperation = {
    type request = {
      token?: string,
      services?: JSON.t,
      alsoKnownAs?: array<string>,
      rotationKeys?: array<string>,
      verificationMethods?: JSON.t,
    }
    type response = ComponentSchemas.ComAtprotoIdentitySignPlcOperationResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoIdentitySignPlcOperation_send"
  }

  module ComAtprotoIdentitySubmitPlcOperation = {
    type request = {
      operation: JSON.t,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoIdentitySubmitPlcOperation_send"
  }

  module ComAtprotoIdentityUpdateHandle = {
    type request = {
      handle: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoIdentityUpdateHandle_send"
  }

}

module ComAtprotoLabel = {
  module ComAtprotoLabelQueryLabels = {
    type request = {
      limit?: int,
      cursor?: string,
      sources?: array<string>,
      uriPatterns: array<string>,
    }
    type response = ComponentSchemas.ComAtprotoLabelQueryLabelsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoLabelQueryLabels_send"
  }

}

module ComAtprotoModeration = {
  module ComAtprotoModerationCreateReport = {
    type request = {
      reason?: string,
      modTool?: ComponentSchemas.ComAtprotoModerationCreateReportModTool.t,
      subject: JSON.t,
      reasonType: ComponentSchemas.ComAtprotoModerationDefsReasonType.t,
    }
    type response = ComponentSchemas.ComAtprotoModerationCreateReportResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoModerationCreateReport_send"
  }

}

module ComAtprotoRepo = {
  module ComAtprotoRepoApplyWrites = {
    type request = {
      repo: string,
      writes: array<JSON.t>,
      validate?: bool,
      swapCommit?: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoApplyWritesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoApplyWrites_send"
  }

  module ComAtprotoRepoCreateRecord = {
    type request = {
      repo: string,
      rkey?: string,
      record: JSON.t,
      validate?: bool,
      collection: string,
      swapCommit?: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoCreateRecordResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoCreateRecord_send"
  }

  module ComAtprotoRepoDeleteRecord = {
    type request = {
      repo: string,
      rkey: string,
      collection: string,
      swapCommit?: string,
      swapRecord?: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoDeleteRecordResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoDeleteRecord_send"
  }

  module ComAtprotoRepoDescribeRepo = {
    type request = {
      repo: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoDescribeRepoResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoDescribeRepo_send"
  }

  module ComAtprotoRepoGetRecord = {
    type request = {
      cid?: string,
      repo: string,
      rkey: string,
      collection: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoGetRecordResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoGetRecord_send"
  }

  module ComAtprotoRepoImportRepo = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoImportRepo_send"
  }

  module ComAtprotoRepoListMissingBlobs = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoListMissingBlobsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoListMissingBlobs_send"
  }

  module ComAtprotoRepoListRecords = {
    type request = {
      repo: string,
      limit?: int,
      cursor?: string,
      reverse?: bool,
      collection: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoListRecordsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoListRecords_send"
  }

  module ComAtprotoRepoPutRecord = {
    type request = {
      repo: string,
      rkey: string,
      record: JSON.t,
      validate?: bool,
      collection: string,
      swapCommit?: string,
      swapRecord?: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoCreateRecordResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoPutRecord_send"
  }

  module ComAtprotoRepoUploadBlob = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoRepoUploadBlobResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoRepoUploadBlob_send"
  }

}

module ComAtprotoServer = {
  module ComAtprotoServerActivateAccount = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerActivateAccount_send"
  }

  module ComAtprotoServerCheckAccountStatus = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoServerCheckAccountStatusResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerCheckAccountStatus_send"
  }

  module ComAtprotoServerConfirmEmail = {
    type request = {
      email: string,
      token: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerConfirmEmail_send"
  }

  module ComAtprotoServerCreateAccount = {
    type request = {
      did?: string,
      email?: string,
      plcOp?: JSON.t,
      handle: string,
      password?: string,
      inviteCode?: string,
      recoveryKey?: string,
      verificationCode?: string,
      verificationPhone?: string,
    }
    type response = ComponentSchemas.ComAtprotoServerCreateAccountResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerCreateAccount_send"
  }

  module ComAtprotoServerCreateAppPassword = {
    type request = {
      name: string,
      privileged?: bool,
    }
    type response = ComponentSchemas.ComAtprotoServerCreateAppPasswordAppPassword.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerCreateAppPassword_send"
  }

  module ComAtprotoServerCreateInviteCode = {
    type request = {
      useCount: int,
      forAccount?: string,
    }
    type response = ComponentSchemas.ComAtprotoServerCreateInviteCodeResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerCreateInviteCode_send"
  }

  module ComAtprotoServerCreateInviteCodes = {
    type request = {
      useCount: int,
      codeCount: int,
      forAccounts?: array<string>,
    }
    type response = ComponentSchemas.ComAtprotoServerCreateInviteCodesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerCreateInviteCodes_send"
  }

  module ComAtprotoServerCreateSession = {
    type request = {
      password: string,
      identifier: string,
      allowTakendown?: bool,
      authFactorToken?: string,
    }
    type response = ComponentSchemas.ComAtprotoServerCreateSessionResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerCreateSession_send"
  }

  module ComAtprotoServerDeactivateAccount = {
    type request = {
      deleteAfter?: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerDeactivateAccount_send"
  }

  module ComAtprotoServerDeleteAccount = {
    type request = {
      did: string,
      token: string,
      password: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerDeleteAccount_send"
  }

  module ComAtprotoServerDeleteSession = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerDeleteSession_send"
  }

  module ComAtprotoServerDescribeServer = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoServerDescribeServerResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerDescribeServer_send"
  }

  module ComAtprotoServerGetAccountInviteCodes = {
    type request = {
      includeUsed?: bool,
      createAvailable?: bool,
    }
    type response = ComponentSchemas.ComAtprotoServerGetAccountInviteCodesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerGetAccountInviteCodes_send"
  }

  module ComAtprotoServerGetServiceAuth = {
    type request = {
      aud: string,
      exp?: int,
      lxm?: string,
    }
    type response = ComponentSchemas.AppBskyContactVerifyPhoneResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerGetServiceAuth_send"
  }

  module ComAtprotoServerGetSession = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoServerGetSessionResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerGetSession_send"
  }

  module ComAtprotoServerListAppPasswords = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoServerListAppPasswordsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerListAppPasswords_send"
  }

  module ComAtprotoServerRefreshSession = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoServerCreateSessionResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerRefreshSession_send"
  }

  module ComAtprotoServerRequestAccountDelete = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerRequestAccountDelete_send"
  }

  module ComAtprotoServerRequestEmailConfirmation = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerRequestEmailConfirmation_send"
  }

  module ComAtprotoServerRequestEmailUpdate = {
    type request = unit
    type response = ComponentSchemas.ComAtprotoServerRequestEmailUpdateResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerRequestEmailUpdate_send"
  }

  module ComAtprotoServerRequestPasswordReset = {
    type request = {
      email: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerRequestPasswordReset_send"
  }

  module ComAtprotoServerReserveSigningKey = {
    type request = {
      did?: string,
    }
    type response = ComponentSchemas.ComAtprotoServerReserveSigningKeyResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerReserveSigningKey_send"
  }

  module ComAtprotoServerResetPassword = {
    type request = {
      token: string,
      password: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerResetPassword_send"
  }

  module ComAtprotoServerRevokeAppPassword = {
    type request = {
      name: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerRevokeAppPassword_send"
  }

  module ComAtprotoServerUpdateEmail = {
    type request = {
      email: string,
      token?: string,
      emailAuthFactor?: bool,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoServerUpdateEmail_send"
  }

}

module ComAtprotoSync = {
  module ComAtprotoSyncGetBlob = {
    type request = {
      cid: string,
      did: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncGetBlob_send"
  }

  module ComAtprotoSyncGetBlocks = {
    type request = {
      did: string,
      cids: array<string>,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncGetBlocks_send"
  }

  module ComAtprotoSyncGetHostStatus = {
    type request = {
      hostname: string,
    }
    type response = ComponentSchemas.ComAtprotoSyncListHostsHost.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncGetHostStatus_send"
  }

  module ComAtprotoSyncGetLatestCommit = {
    type request = {
      did: string,
    }
    type response = ComponentSchemas.ComAtprotoRepoDefsCommitMeta.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncGetLatestCommit_send"
  }

  module ComAtprotoSyncGetRecord = {
    type request = {
      did: string,
      rkey: string,
      collection: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncGetRecord_send"
  }

  module ComAtprotoSyncGetRepo = {
    type request = {
      did: string,
      since?: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncGetRepo_send"
  }

  module ComAtprotoSyncGetRepoStatus = {
    type request = {
      did: string,
    }
    type response = ComponentSchemas.ComAtprotoSyncGetRepoStatusResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncGetRepoStatus_send"
  }

  module ComAtprotoSyncListBlobs = {
    type request = {
      did: string,
      limit?: int,
      since?: string,
      cursor?: string,
    }
    type response = ComponentSchemas.ComAtprotoSyncListBlobsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncListBlobs_send"
  }

  module ComAtprotoSyncListHosts = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.ComAtprotoSyncListHostsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncListHosts_send"
  }

  module ComAtprotoSyncListRepos = {
    type request = {
      limit?: int,
      cursor?: string,
    }
    type response = ComponentSchemas.ComAtprotoSyncListReposResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncListRepos_send"
  }

  module ComAtprotoSyncListReposByCollection = {
    type request = {
      limit?: int,
      cursor?: string,
      collection: string,
    }
    type response = ComponentSchemas.ComAtprotoSyncListReposByCollectionResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncListReposByCollection_send"
  }

  module ComAtprotoSyncNotifyOfUpdate = {
    type request = {
      hostname: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncNotifyOfUpdate_send"
  }

  module ComAtprotoSyncRequestCrawl = {
    type request = {
      hostname: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "comAtprotoSyncRequestCrawl_send"
  }

}

