(* Generated by the OCaml generator. Do not edit. *)
open! Melange_json.Primitives

module OAuthScope = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module OAuthScopes = struct
  type t = OAuthScope.t array
  let of_json = (array_of_json OAuthScope.of_json)
  let to_json = (array_to_json OAuthScope.to_json)
end
let oAuthScopes_of_json = OAuthScopes.of_json
let oAuthScopes_to_json = OAuthScopes.to_json

module AccountRole = struct
  type t = {
    color : string;
    id : string;
    name : string;
  } [@@deriving json]
end
let accountRole_of_json = AccountRole.of_json
let accountRole_to_json = AccountRole.to_json

module CustomEmoji = struct
  type t = {
    shortcode : string;
    static_url : string;
    url : string;
    visible_in_picker : bool;
    category : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let customEmoji_of_json = CustomEmoji.of_json
let customEmoji_to_json = CustomEmoji.to_json

module FeatureApprovalAutomaticEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module FeatureApprovalCurrentUserEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module QuoteApprovalAutomaticEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module FeatureApproval = struct
  type t = {
    automatic : FeatureApprovalAutomaticEnum.t array;
    current_user : FeatureApprovalCurrentUserEnum.t;
    manual : QuoteApprovalAutomaticEnum.t array;
  } [@@deriving json]
end
let featureApproval_of_json = FeatureApproval.of_json
let featureApproval_to_json = FeatureApproval.to_json

module Field = struct
  type t = {
    name : string;
    value : string;
    verified_at : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let field_of_json = Field.of_json
let field_to_json = Field.to_json

module Account = struct
  type t = {
    acct : string;
    avatar : string;
    avatar_static : string;
    bot : bool;
    created_at : string;
    display_name : string;
    emojis : CustomEmoji.t array;
    fields : Field.t array;
    followers_count : int;
    following_count : int;
    group : bool;
    header : string;
    header_static : string;
    id : string;
    locked : bool;
    note : string;
    statuses_count : int;
    uri : string;
    username : string;
    avatar_description : string option; [@json.option] [@json.drop_default]
    discoverable : bool option; [@json.option] [@json.drop_default]
    feature_approval : FeatureApproval.t option; [@json.option] [@json.drop_default]
    header_description : string option; [@json.option] [@json.drop_default]
    hide_collections : bool option; [@json.option] [@json.drop_default]
    indexable : bool option; [@json.option] [@json.drop_default]
    last_status_at : string option; [@json.option] [@json.drop_default]
    limited : bool option; [@json.option] [@json.drop_default]
    memorial : bool option; [@json.option] [@json.drop_default]
    moved : t option; [@json.option] [@json.drop_default]
    noindex : bool option; [@json.option] [@json.drop_default]
    roles : AccountRole.t array option; [@json.option] [@json.drop_default]
    show_featured : bool option; [@json.option] [@json.drop_default]
    show_media : bool option; [@json.option] [@json.drop_default]
    show_media_replies : bool option; [@json.option] [@json.drop_default]
    suspended : bool option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let account_of_json = Account.of_json
let account_to_json = Account.to_json

module CredentialAccountSourceQuotePolicyEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module StatusVisibilityEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module CredentialAccountSource = struct
  type t = {
    fields : Field.t array;
    follow_requests_count : int;
    note : string;
    privacy : StatusVisibilityEnum.t;
    sensitive : bool;
    attribution_domains : string array option; [@json.option] [@json.drop_default]
    discoverable : bool option; [@json.option] [@json.drop_default]
    hide_collections : bool option; [@json.option] [@json.drop_default]
    indexable : bool option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    quote_policy : CredentialAccountSourceQuotePolicyEnum.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let credentialAccountSource_of_json = CredentialAccountSource.of_json
let credentialAccountSource_to_json = CredentialAccountSource.to_json

module Role = struct
  type t = {
    color : string;
    highlighted : bool;
    id : string;
    name : string;
    permissions : string;
    collection_limit : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let role_of_json = Role.of_json
let role_to_json = Role.to_json

module CredentialAccount = struct
  type t = {
    acct : string;
    avatar : string;
    avatar_static : string;
    bot : bool;
    created_at : string;
    display_name : string;
    emojis : CustomEmoji.t array;
    fields : Field.t array;
    followers_count : int;
    following_count : int;
    group : bool;
    header : string;
    header_static : string;
    id : string;
    locked : bool;
    note : string;
    role : Role.t;
    source : CredentialAccountSource.t;
    statuses_count : int;
    uri : string;
    username : string;
    avatar_description : string option; [@json.option] [@json.drop_default]
    discoverable : bool option; [@json.option] [@json.drop_default]
    feature_approval : FeatureApproval.t option; [@json.option] [@json.drop_default]
    header_description : string option; [@json.option] [@json.drop_default]
    hide_collections : bool option; [@json.option] [@json.drop_default]
    indexable : bool option; [@json.option] [@json.drop_default]
    last_status_at : string option; [@json.option] [@json.drop_default]
    limited : bool option; [@json.option] [@json.drop_default]
    memorial : bool option; [@json.option] [@json.drop_default]
    moved : Account.t option; [@json.option] [@json.drop_default]
    noindex : bool option; [@json.option] [@json.drop_default]
    roles : AccountRole.t array option; [@json.option] [@json.drop_default]
    show_featured : bool option; [@json.option] [@json.drop_default]
    show_media : bool option; [@json.option] [@json.drop_default]
    show_media_replies : bool option; [@json.option] [@json.drop_default]
    suspended : bool option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let credentialAccount_of_json = CredentialAccount.of_json
let credentialAccount_to_json = CredentialAccount.to_json

module MutedAccount = struct
  type t = {
    acct : string;
    avatar : string;
    avatar_static : string;
    bot : bool;
    created_at : string;
    display_name : string;
    emojis : CustomEmoji.t array;
    fields : Field.t array;
    followers_count : int;
    following_count : int;
    group : bool;
    header : string;
    header_static : string;
    id : string;
    locked : bool;
    note : string;
    statuses_count : int;
    uri : string;
    username : string;
    avatar_description : string option; [@json.option] [@json.drop_default]
    discoverable : bool option; [@json.option] [@json.drop_default]
    feature_approval : FeatureApproval.t option; [@json.option] [@json.drop_default]
    header_description : string option; [@json.option] [@json.drop_default]
    hide_collections : bool option; [@json.option] [@json.drop_default]
    indexable : bool option; [@json.option] [@json.drop_default]
    last_status_at : string option; [@json.option] [@json.drop_default]
    limited : bool option; [@json.option] [@json.drop_default]
    memorial : bool option; [@json.option] [@json.drop_default]
    moved : Account.t option; [@json.option] [@json.drop_default]
    mute_expires_at : string option; [@json.option] [@json.drop_default]
    noindex : bool option; [@json.option] [@json.drop_default]
    roles : AccountRole.t array option; [@json.option] [@json.drop_default]
    show_featured : bool option; [@json.option] [@json.drop_default]
    show_media : bool option; [@json.option] [@json.drop_default]
    show_media_replies : bool option; [@json.option] [@json.drop_default]
    suspended : bool option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let mutedAccount_of_json = MutedAccount.of_json
let mutedAccount_to_json = MutedAccount.to_json

module PartialAccountWithAvatar = struct
  type t = {
    acct : string option; [@json.option] [@json.drop_default]
    avatar : string option; [@json.option] [@json.drop_default]
    avatar_description : string option; [@json.option] [@json.drop_default]
    avatar_static : string option; [@json.option] [@json.drop_default]
    bot : bool option; [@json.option] [@json.drop_default]
    id : string option; [@json.option] [@json.drop_default]
    locked : bool option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let partialAccountWithAvatar_of_json = PartialAccountWithAvatar.of_json
let partialAccountWithAvatar_to_json = PartialAccountWithAvatar.to_json

module AccountWarningActionEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module AppealStateEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module Appeal = struct
  type t = {
    state : AppealStateEnum.t;
    text : string;
  } [@@deriving json]
end
let appeal_of_json = Appeal.of_json
let appeal_to_json = Appeal.to_json

module AccountWarning = struct
  type t = {
    action : AccountWarningActionEnum.t;
    created_at : string;
    id : string;
    target_account : Account.t;
    text : string;
    appeal : Appeal.t option; [@json.option] [@json.drop_default]
    status_ids : string array option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let accountWarning_of_json = AccountWarning.of_json
let accountWarning_to_json = AccountWarning.to_json

module AdminIp = struct
  type t = {
    ip : string;
    used_at : string;
  } [@@deriving json]
end
let adminIp_of_json = AdminIp.of_json
let adminIp_to_json = AdminIp.to_json

module AdminAccount = struct
  type t = {
    account : Account.t;
    approved : bool;
    confirmed : bool;
    created_at : string;
    disabled : bool;
    email : string;
    id : string;
    ips : AdminIp.t array;
    locale : string;
    role : Role.t;
    sensitized : bool;
    silenced : bool;
    suspended : bool;
    username : string;
    created_by_application_id : string option; [@json.option] [@json.drop_default]
    domain : string option; [@json.option] [@json.drop_default]
    invite_request : string option; [@json.option] [@json.drop_default]
    invited_by_account_id : string option; [@json.option] [@json.drop_default]
    ip : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let adminAccount_of_json = AdminAccount.of_json
let adminAccount_to_json = AdminAccount.to_json

module AdminCanonicalEmailBlock = struct
  type t = {
    canonical_email_hash : string;
    id : string;
  } [@@deriving json]
end
let adminCanonicalEmailBlock_of_json = AdminCanonicalEmailBlock.of_json
let adminCanonicalEmailBlock_to_json = AdminCanonicalEmailBlock.to_json

module AdminCohortFrequencyEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module CohortData = struct
  type t = {
    date : string;
    rate : float;
    value : string;
  } [@@deriving json]
end
let cohortData_of_json = CohortData.of_json
let cohortData_to_json = CohortData.to_json

module AdminCohort = struct
  type t = {
    data : CohortData.t array;
    frequency : AdminCohortFrequencyEnum.t;
    period : string;
  } [@@deriving json]
end
let adminCohort_of_json = AdminCohort.of_json
let adminCohort_to_json = AdminCohort.to_json

module AdminDimensionData = struct
  type t = {
    human_key : string;
    key : string;
    value : string;
    human_value : string option; [@json.option] [@json.drop_default]
    unit : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let adminDimensionData_of_json = AdminDimensionData.of_json
let adminDimensionData_to_json = AdminDimensionData.to_json

module AdminDimension = struct
  type t = {
    data : AdminDimensionData.t array;
    key : string;
  } [@@deriving json]
end
let adminDimension_of_json = AdminDimension.of_json
let adminDimension_to_json = AdminDimension.to_json

module AdminDomainAllow = struct
  type t = {
    created_at : string;
    domain : string;
    id : string;
  } [@@deriving json]
end
let adminDomainAllow_of_json = AdminDomainAllow.of_json
let adminDomainAllow_to_json = AdminDomainAllow.to_json

module AdminDomainBlockSeverityEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module AdminDomainBlock = struct
  type t = {
    created_at : string;
    domain : string;
    id : string;
    obfuscate : bool;
    reject_media : bool;
    reject_reports : bool;
    severity : AdminDomainBlockSeverityEnum.t;
    digest : string option; [@json.option] [@json.drop_default]
    private_comment : string option; [@json.option] [@json.drop_default]
    public_comment : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let adminDomainBlock_of_json = AdminDomainBlock.of_json
let adminDomainBlock_to_json = AdminDomainBlock.to_json

module AdminEmailDomainBlockHistory = struct
  type t = {
    accounts : string;
    day : string;
    uses : string;
  } [@@deriving json]
end
let adminEmailDomainBlockHistory_of_json = AdminEmailDomainBlockHistory.of_json
let adminEmailDomainBlockHistory_to_json = AdminEmailDomainBlockHistory.to_json

module AdminEmailDomainBlock = struct
  type t = {
    created_at : string;
    domain : string;
    history : AdminEmailDomainBlockHistory.t array;
    id : string;
  } [@@deriving json]
end
let adminEmailDomainBlock_of_json = AdminEmailDomainBlock.of_json
let adminEmailDomainBlock_to_json = AdminEmailDomainBlock.to_json

module AdminIpBlockSeverityEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module AdminIpBlock = struct
  type t = {
    comment : string;
    created_at : string;
    id : string;
    ip : string;
    severity : AdminIpBlockSeverityEnum.t;
    expires_at : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let adminIpBlock_of_json = AdminIpBlock.of_json
let adminIpBlock_to_json = AdminIpBlock.to_json

module AdminMeasureData = struct
  type t = {
    date : string;
    value : string;
  } [@@deriving json]
end
let adminMeasureData_of_json = AdminMeasureData.of_json
let adminMeasureData_to_json = AdminMeasureData.to_json

module AdminMeasure = struct
  type t = {
    data : AdminMeasureData.t array;
    key : string;
    total : string;
    human_value : string option; [@json.option] [@json.drop_default]
    previous_total : string option; [@json.option] [@json.drop_default]
    unit : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let adminMeasure_of_json = AdminMeasure.of_json
let adminMeasure_to_json = AdminMeasure.to_json

module ReportCategoryEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module Rule = struct
  type t = {
    id : string;
    text : string;
    hint : string option; [@json.option] [@json.drop_default]
    translations : Melange_json.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let rule_of_json = Rule.of_json
let rule_to_json = Rule.to_json

module CollectionItemStateEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module CollectionItem = struct
  type t = {
    created_at : string;
    id : string;
    state : CollectionItemStateEnum.t;
    account_id : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let collectionItem_of_json = CollectionItem.of_json
let collectionItem_to_json = CollectionItem.to_json

module ShallowTag = struct
  type t = {
    name : string;
    url : string;
  } [@@deriving json]
end
let shallowTag_of_json = ShallowTag.of_json
let shallowTag_to_json = ShallowTag.to_json

module Collection = struct
  type t = {
    account_id : string;
    created_at : string;
    description : string;
    discoverable : bool;
    id : string;
    item_count : int;
    items : CollectionItem.t array;
    local : bool;
    name : string;
    sensitive : bool;
    updated_at : string;
    uri : string;
    language : string option; [@json.option] [@json.drop_default]
    tag : ShallowTag.t option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let collection_of_json = Collection.of_json
let collection_to_json = Collection.to_json

module FilterContextEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module FilterFilterActionEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module FilterKeyword = struct
  type t = {
    id : string;
    keyword : string;
    whole_word : bool;
  } [@@deriving json]
end
let filterKeyword_of_json = FilterKeyword.of_json
let filterKeyword_to_json = FilterKeyword.to_json

module FilterStatus = struct
  type t = {
    id : string;
    status_id : string;
  } [@@deriving json]
end
let filterStatus_of_json = FilterStatus.of_json
let filterStatus_to_json = FilterStatus.to_json

module Filter = struct
  type t = {
    context : FilterContextEnum.t array;
    filter_action : FilterFilterActionEnum.t;
    id : string;
    title : string;
    expires_at : string option; [@json.option] [@json.drop_default]
    keywords : FilterKeyword.t array option; [@json.option] [@json.drop_default]
    statuses : FilterStatus.t array option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let filter_of_json = Filter.of_json
let filter_to_json = Filter.to_json

module FilterResult = struct
  type t = {
    filter : Filter.t;
    keyword_matches : string array option; [@json.option] [@json.drop_default]
    status_matches : string array option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let filterResult_of_json = FilterResult.of_json
let filterResult_to_json = FilterResult.to_json

module MediaAttachmentMetaFocus = struct
  type t = {
    x : float option; [@json.option] [@json.drop_default]
    y : float option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let mediaAttachmentMetaFocus_of_json = MediaAttachmentMetaFocus.of_json
let mediaAttachmentMetaFocus_to_json = MediaAttachmentMetaFocus.to_json

module MetaDetails = struct
  type t = {
    aspect : float option; [@json.option] [@json.drop_default]
    bitrate : int option; [@json.option] [@json.drop_default]
    duration : float option; [@json.option] [@json.drop_default]
    frame_rate : string option; [@json.option] [@json.drop_default]
    height : int option; [@json.option] [@json.drop_default]
    width : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let metaDetails_of_json = MetaDetails.of_json
let metaDetails_to_json = MetaDetails.to_json

module MediaAttachmentMeta = struct
  type t = {
    small : MetaDetails.t option; [@json.option] [@json.drop_default]
    original : MetaDetails.t option; [@json.option] [@json.drop_default]
    focus : MediaAttachmentMetaFocus.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let mediaAttachmentMeta_of_json = MediaAttachmentMeta.of_json
let mediaAttachmentMeta_to_json = MediaAttachmentMeta.to_json

module MediaAttachmentTypeEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module MediaAttachment = struct
  type t = {
    id : string;
    type_ : MediaAttachmentTypeEnum.t; [@json.key "type"]
    blurhash : string option; [@json.option] [@json.drop_default]
    description : string option; [@json.option] [@json.drop_default]
    meta : MediaAttachmentMeta.t option; [@json.option] [@json.drop_default]
    preview_url : string option; [@json.option] [@json.drop_default]
    remote_url : string option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let mediaAttachment_of_json = MediaAttachment.of_json
let mediaAttachment_to_json = MediaAttachment.to_json

module PollOption = struct
  type t = {
    title : string;
    votes_count : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let pollOption_of_json = PollOption.of_json
let pollOption_to_json = PollOption.to_json

module Poll = struct
  type t = {
    emojis : CustomEmoji.t array;
    expired : bool;
    id : string;
    multiple : bool;
    options : PollOption.t array;
    votes_count : int;
    expires_at : string option; [@json.option] [@json.drop_default]
    own_votes : int array option; [@json.option] [@json.drop_default]
    voted : bool option; [@json.option] [@json.drop_default]
    voters_count : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let poll_of_json = Poll.of_json
let poll_to_json = Poll.to_json

module PreviewCardAuthor = struct
  type t = {
    name : string;
    url : string;
    account : Account.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let previewCardAuthor_of_json = PreviewCardAuthor.of_json
let previewCardAuthor_to_json = PreviewCardAuthor.to_json

module TrendsLinkTypeEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module PreviewCard = struct
  type t = {
    description : string;
    embed_url : string;
    height : int;
    html : string;
    provider_name : string;
    provider_url : string;
    title : string;
    type_ : TrendsLinkTypeEnum.t; [@json.key "type"]
    url : string;
    width : int;
    author_name : string option; [@json.option] [@json.drop_default]
    author_url : string option; [@json.option] [@json.drop_default]
    authors : PreviewCardAuthor.t array option; [@json.option] [@json.drop_default]
    blurhash : string option; [@json.option] [@json.drop_default]
    image : string option; [@json.option] [@json.drop_default]
    missing_attribution : bool option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let previewCard_of_json = PreviewCard.of_json
let previewCard_to_json = PreviewCard.to_json

module QuoteApprovalCurrentUserEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module QuoteApproval = struct
  type t = {
    automatic : QuoteApprovalAutomaticEnum.t array;
    current_user : QuoteApprovalCurrentUserEnum.t;
    manual : QuoteApprovalAutomaticEnum.t array;
  } [@@deriving json]
end
let quoteApproval_of_json = QuoteApproval.of_json
let quoteApproval_to_json = QuoteApproval.to_json

module StatusApplication = struct
  type t = {
    name : string;
    website : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let statusApplication_of_json = StatusApplication.of_json
let statusApplication_to_json = StatusApplication.to_json

module StatusMention = struct
  type t = {
    acct : string;
    id : string;
    url : string;
    username : string;
  } [@@deriving json]
end
let statusMention_of_json = StatusMention.of_json
let statusMention_to_json = StatusMention.to_json

module StatusTag = struct
  type t = {
    name : string;
    url : string;
  } [@@deriving json]
end
let statusTag_of_json = StatusTag.of_json
let statusTag_to_json = StatusTag.to_json

module Status = struct
  type t = {
    account : Account.t;
    content : string;
    created_at : string;
    emojis : CustomEmoji.t array;
    favourites_count : int;
    id : string;
    media_attachments : MediaAttachment.t array;
    mentions : StatusMention.t array;
    reblogs_count : int;
    replies_count : int;
    sensitive : bool;
    spoiler_text : string;
    tags : StatusTag.t array;
    uri : string;
    visibility : StatusVisibilityEnum.t;
    application : StatusApplication.t option; [@json.option] [@json.drop_default]
    bookmarked : bool option; [@json.option] [@json.drop_default]
    card : PreviewCard.t option; [@json.option] [@json.drop_default]
    edited_at : string option; [@json.option] [@json.drop_default]
    favourited : bool option; [@json.option] [@json.drop_default]
    filtered : FilterResult.t array option; [@json.option] [@json.drop_default]
    in_reply_to_account_id : string option; [@json.option] [@json.drop_default]
    in_reply_to_id : string option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    muted : bool option; [@json.option] [@json.drop_default]
    pinned : bool option; [@json.option] [@json.drop_default]
    poll : Poll.t option; [@json.option] [@json.drop_default]
    quote : Melange_json.t option; [@json.option] [@json.drop_default]
    quote_approval : QuoteApproval.t option; [@json.option] [@json.drop_default]
    quotes_count : int option; [@json.option] [@json.drop_default]
    reblog : t option; [@json.option] [@json.drop_default]
    reblogged : bool option; [@json.option] [@json.drop_default]
    tagged_collections : Collection.t array option; [@json.option] [@json.drop_default]
    text : string option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let status_of_json = Status.of_json
let status_to_json = Status.to_json

module AdminReport = struct
  type t = {
    account : AdminAccount.t;
    action_taken : bool;
    category : ReportCategoryEnum.t;
    comment : string;
    created_at : string;
    forwarded : bool;
    id : string;
    rules : Rule.t array;
    statuses : Status.t array;
    target_account : AdminAccount.t;
    updated_at : string;
    action_taken_at : string option; [@json.option] [@json.drop_default]
    action_taken_by_account : AdminAccount.t option; [@json.option] [@json.drop_default]
    assigned_account : AdminAccount.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let adminReport_of_json = AdminReport.of_json
let adminReport_to_json = AdminReport.to_json

module AnnouncementAccount = struct
  type t = {
    acct : string;
    id : string;
    url : string;
    username : string;
  } [@@deriving json]
end
let announcementAccount_of_json = AnnouncementAccount.of_json
let announcementAccount_to_json = AnnouncementAccount.to_json

module AnnouncementStatus = struct
  type t = {
    id : string;
    url : string;
  } [@@deriving json]
end
let announcementStatus_of_json = AnnouncementStatus.of_json
let announcementStatus_to_json = AnnouncementStatus.to_json

module Reaction = struct
  type t = {
    count : int;
    name : string;
    me : bool option; [@json.option] [@json.drop_default]
    static_url : string option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let reaction_of_json = Reaction.of_json
let reaction_to_json = Reaction.to_json

module Announcement = struct
  type t = {
    all_day : bool;
    content : string;
    emojis : CustomEmoji.t array;
    id : string;
    mentions : AnnouncementAccount.t array;
    published_at : string;
    reactions : Reaction.t array;
    statuses : AnnouncementStatus.t array;
    tags : StatusTag.t array;
    updated_at : string;
    ends_at : string option; [@json.option] [@json.drop_default]
    read : bool option; [@json.option] [@json.drop_default]
    starts_at : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let announcement_of_json = Announcement.of_json
let announcement_to_json = Announcement.to_json

module AnnualReportData = struct
  type t = {
    archetype : string option; [@json.option] [@json.drop_default]
    type_distribution : Melange_json.t option; [@json.option] [@json.drop_default]
    top_statuses : Melange_json.t option; [@json.option] [@json.drop_default]
    most_used_apps : Melange_json.t array option; [@json.option] [@json.drop_default]
    commonly_interacted_with_accounts : Melange_json.t array option; [@json.option] [@json.drop_default]
    time_series : Melange_json.t array option; [@json.option] [@json.drop_default]
    top_hashtags : Melange_json.t array option; [@json.option] [@json.drop_default]
    most_reblogged_accounts : Melange_json.t array option; [@json.option] [@json.drop_default]
    percentiles : float option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let annualReportData_of_json = AnnualReportData.of_json
let annualReportData_to_json = AnnualReportData.to_json

module AnnualReport = struct
  type t = {
    account_id : string option; [@json.option] [@json.drop_default]
    data : AnnualReportData.t option; [@json.option] [@json.drop_default]
    schema_version : int option; [@json.option] [@json.drop_default]
    share_url : string option; [@json.option] [@json.drop_default]
    year : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let annualReport_of_json = AnnualReport.of_json
let annualReport_to_json = AnnualReport.to_json

module Application = struct
  type t = {
    id : string;
    name : string;
    redirect_uri : string option; [@json.option] [@json.drop_default]
    redirect_uris : string array option; [@json.option] [@json.drop_default]
    scopes : OAuthScopes.t option; [@json.option] [@json.drop_default]
    vapid_key : string option; [@json.option] [@json.drop_default]
    website : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let application_of_json = Application.of_json
let application_to_json = Application.to_json

module CredentialApplication = struct
  type t = {
    client_id : string;
    client_secret : string;
    id : string;
    name : string;
    client_secret_expires_at : int option; [@json.option] [@json.drop_default]
    redirect_uri : string option; [@json.option] [@json.drop_default]
    redirect_uris : string array option; [@json.option] [@json.drop_default]
    scopes : OAuthScopes.t option; [@json.option] [@json.drop_default]
    vapid_key : string option; [@json.option] [@json.drop_default]
    website : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let credentialApplication_of_json = CredentialApplication.of_json
let credentialApplication_to_json = CredentialApplication.to_json

module AsyncRefreshStatusEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module AsyncRefresh = struct
  type t = {
    id : string;
    status : AsyncRefreshStatusEnum.t;
    result_count : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let asyncRefresh_of_json = AsyncRefresh.of_json
let asyncRefresh_to_json = AsyncRefresh.to_json

module CollectionWithAccounts = struct
  type t = {
    accounts : Account.t array;
    collection : Collection.t;
  } [@@deriving json]
end
let collectionWithAccounts_of_json = CollectionWithAccounts.of_json
let collectionWithAccounts_to_json = CollectionWithAccounts.to_json

module Context = struct
  type t = {
    ancestors : Status.t array;
    descendants : Status.t array;
  } [@@deriving json]
end
let context_of_json = Context.of_json
let context_to_json = Context.to_json

module Conversation = struct
  type t = {
    accounts : Account.t array;
    id : string;
    unread : bool;
    last_status : Status.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let conversation_of_json = Conversation.of_json
let conversation_to_json = Conversation.to_json

module DomainBlockSeverityEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module DomainBlock = struct
  type t = {
    digest : string;
    domain : string;
    severity : DomainBlockSeverityEnum.t;
    comment : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let domainBlock_of_json = DomainBlock.of_json
let domainBlock_to_json = DomainBlock.to_json

module Error = struct
  type t = {
    error : string;
    error_description : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let error_of_json = Error.of_json
let error_to_json = Error.to_json

module ExtendedDescription = struct
  type t = {
    content : string;
    updated_at : string;
  } [@@deriving json]
end
let extendedDescription_of_json = ExtendedDescription.of_json
let extendedDescription_to_json = ExtendedDescription.to_json

module FamiliarFollowers = struct
  type t = {
    accounts : Account.t array;
    id : string;
  } [@@deriving json]
end
let familiarFollowers_of_json = FamiliarFollowers.of_json
let familiarFollowers_to_json = FamiliarFollowers.to_json

module FeaturedTag = struct
  type t = {
    id : string;
    name : string;
    statuses_count : string;
    url : string;
    last_status_at : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let featuredTag_of_json = FeaturedTag.of_json
let featuredTag_to_json = FeaturedTag.to_json

module IdentityProof = struct
  type t = {
    profile_url : string;
    proof_url : string;
    provider : string;
    provider_username : string;
    updated_at : string;
  } [@@deriving json]
end
let identityProof_of_json = IdentityProof.of_json
let identityProof_to_json = IdentityProof.to_json

module InstanceApiVersions = struct
  type t = {
    mastodon : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceApiVersions_of_json = InstanceApiVersions.of_json
let instanceApiVersions_to_json = InstanceApiVersions.to_json

module InstanceConfigurationAccounts = struct
  type t = {
    max_featured_tags : int;
    max_display_name_length : int option; [@json.option] [@json.drop_default]
    max_note_length : int option; [@json.option] [@json.drop_default]
    max_pinned_statuses : int option; [@json.option] [@json.drop_default]
    max_profile_fields : int option; [@json.option] [@json.drop_default]
    profile_field_name_limit : int option; [@json.option] [@json.drop_default]
    profile_field_value_limit : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceConfigurationAccounts_of_json = InstanceConfigurationAccounts.of_json
let instanceConfigurationAccounts_to_json = InstanceConfigurationAccounts.to_json

module InstanceConfigurationMediaAttachments = struct
  type t = {
    image_matrix_limit : int;
    image_size_limit : int;
    supported_mime_types : string array;
    video_frame_rate_limit : int;
    video_matrix_limit : int;
    video_size_limit : int;
    description_limit : int option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceConfigurationMediaAttachments_of_json = InstanceConfigurationMediaAttachments.of_json
let instanceConfigurationMediaAttachments_to_json = InstanceConfigurationMediaAttachments.to_json

module InstanceConfigurationPolls = struct
  type t = {
    max_characters_per_option : int;
    max_expiration : int;
    max_options : int;
    min_expiration : int;
  } [@@deriving json]
end
let instanceConfigurationPolls_of_json = InstanceConfigurationPolls.of_json
let instanceConfigurationPolls_to_json = InstanceConfigurationPolls.to_json

module InstanceConfigurationStatuses = struct
  type t = {
    characters_reserved_per_url : int;
    max_characters : int;
    max_media_attachments : int;
  } [@@deriving json]
end
let instanceConfigurationStatuses_of_json = InstanceConfigurationStatuses.of_json
let instanceConfigurationStatuses_to_json = InstanceConfigurationStatuses.to_json

module InstanceConfigurationTimelinesAccessHashtagFeeds = struct
  type t = {
    local : string option; [@json.option] [@json.drop_default]
    remote : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceConfigurationTimelinesAccessHashtagFeeds_of_json = InstanceConfigurationTimelinesAccessHashtagFeeds.of_json
let instanceConfigurationTimelinesAccessHashtagFeeds_to_json = InstanceConfigurationTimelinesAccessHashtagFeeds.to_json

module InstanceConfigurationTimelinesAccessLiveFeeds = struct
  type t = {
    local : string option; [@json.option] [@json.drop_default]
    remote : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceConfigurationTimelinesAccessLiveFeeds_of_json = InstanceConfigurationTimelinesAccessLiveFeeds.of_json
let instanceConfigurationTimelinesAccessLiveFeeds_to_json = InstanceConfigurationTimelinesAccessLiveFeeds.to_json

module InstanceConfigurationTimelinesAccess = struct
  type t = {
    live_feeds : InstanceConfigurationTimelinesAccessLiveFeeds.t option; [@json.option] [@json.drop_default]
    hashtag_feeds : InstanceConfigurationTimelinesAccessHashtagFeeds.t option; [@json.option] [@json.drop_default]
    trending_link_feeds : InstanceConfigurationTimelinesAccessHashtagFeeds.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceConfigurationTimelinesAccess_of_json = InstanceConfigurationTimelinesAccess.of_json
let instanceConfigurationTimelinesAccess_to_json = InstanceConfigurationTimelinesAccess.to_json

module InstanceConfigurationTranslation = struct
  type t = {
    enabled : bool;
  } [@@deriving json]
end
let instanceConfigurationTranslation_of_json = InstanceConfigurationTranslation.of_json
let instanceConfigurationTranslation_to_json = InstanceConfigurationTranslation.to_json

module InstanceConfigurationUrls = struct
  type t = {
    about : string option; [@json.option] [@json.drop_default]
    privacy_policy : string option; [@json.option] [@json.drop_default]
    status : string option; [@json.option] [@json.drop_default]
    streaming : string option; [@json.option] [@json.drop_default]
    terms_of_service : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceConfigurationUrls_of_json = InstanceConfigurationUrls.of_json
let instanceConfigurationUrls_to_json = InstanceConfigurationUrls.to_json

module InstanceConfiguration = struct
  type t = {
    accounts : InstanceConfigurationAccounts.t;
    media_attachments : InstanceConfigurationMediaAttachments.t;
    polls : InstanceConfigurationPolls.t;
    statuses : InstanceConfigurationStatuses.t;
    translation : InstanceConfigurationTranslation.t;
    urls : InstanceConfigurationUrls.t;
    limited_federation : bool option; [@json.option] [@json.drop_default]
    timelines_access : InstanceConfigurationTimelinesAccess.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceConfiguration_of_json = InstanceConfiguration.of_json
let instanceConfiguration_to_json = InstanceConfiguration.to_json

module InstanceContact = struct
  type t = {
    email : string;
    account : Account.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceContact_of_json = InstanceContact.of_json
let instanceContact_to_json = InstanceContact.to_json

module InstanceIcon = struct
  type t = {
    size : string;
    src : string;
  } [@@deriving json]
end
let instanceIcon_of_json = InstanceIcon.of_json
let instanceIcon_to_json = InstanceIcon.to_json

module InstanceRegistrations = struct
  type t = {
    approval_required : bool;
    enabled : bool;
    message : string option; [@json.option] [@json.drop_default]
    min_age : int option; [@json.option] [@json.drop_default]
    reason_required : bool option; [@json.option] [@json.drop_default]
    url : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceRegistrations_of_json = InstanceRegistrations.of_json
let instanceRegistrations_to_json = InstanceRegistrations.to_json

module InstanceThumbnailVersions = struct
  type t = {
    _1x : string option; [@json.key "@1x"] [@json.option] [@json.drop_default]
    _2x : string option; [@json.key "@2x"] [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceThumbnailVersions_of_json = InstanceThumbnailVersions.of_json
let instanceThumbnailVersions_to_json = InstanceThumbnailVersions.to_json

module InstanceThumbnail = struct
  type t = {
    url : string;
    blurhash : string option; [@json.option] [@json.drop_default]
    description : string option; [@json.option] [@json.drop_default]
    versions : InstanceThumbnailVersions.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instanceThumbnail_of_json = InstanceThumbnail.of_json
let instanceThumbnail_to_json = InstanceThumbnail.to_json

module InstanceUsageUsers = struct
  type t = {
    active_month : int;
  } [@@deriving json]
end
let instanceUsageUsers_of_json = InstanceUsageUsers.of_json
let instanceUsageUsers_to_json = InstanceUsageUsers.to_json

module InstanceUsage = struct
  type t = {
    users : InstanceUsageUsers.t;
  } [@@deriving json]
end
let instanceUsage_of_json = InstanceUsage.of_json
let instanceUsage_to_json = InstanceUsage.to_json

module Instance = struct
  type t = {
    configuration : InstanceConfiguration.t;
    contact : InstanceContact.t;
    description : string;
    domain : string;
    languages : string array;
    registrations : InstanceRegistrations.t;
    rules : Rule.t array;
    source_url : string;
    thumbnail : InstanceThumbnail.t;
    title : string;
    usage : InstanceUsage.t;
    version : string;
    api_versions : InstanceApiVersions.t option; [@json.option] [@json.drop_default]
    icon : InstanceIcon.t array option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let instance_of_json = Instance.of_json
let instance_to_json = Instance.to_json

module ListRepliesPolicyEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module List = struct
  type t = {
    exclusive : bool;
    id : string;
    replies_policy : ListRepliesPolicyEnum.t;
    title : string;
  } [@@deriving json]
end
let list_of_json = List.of_json
let list_to_json = List.to_json

module Marker = struct
  type t = {
    last_read_id : string;
    updated_at : string;
    version : int;
  } [@@deriving json]
end
let marker_of_json = Marker.of_json
let marker_to_json = Marker.to_json

module NotificationFallback = struct
  type t = {
    title : string;
    details : string option; [@json.option] [@json.drop_default]
    summary : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let notificationFallback_of_json = NotificationFallback.of_json
let notificationFallback_to_json = NotificationFallback.to_json

module NotificationTypeEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module RelationshipSeveranceEventTypeEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module RelationshipSeveranceEvent = struct
  type t = {
    created_at : string;
    followers_count : int;
    following_count : int;
    id : string;
    purged : bool;
    target_name : string;
    type_ : RelationshipSeveranceEventTypeEnum.t; [@json.key "type"]
  } [@@deriving json]
end
let relationshipSeveranceEvent_of_json = RelationshipSeveranceEvent.of_json
let relationshipSeveranceEvent_to_json = RelationshipSeveranceEvent.to_json

module Report = struct
  type t = {
    action_taken : bool;
    category : ReportCategoryEnum.t;
    comment : string;
    created_at : string;
    forwarded : bool;
    id : string;
    target_account : Account.t;
    action_taken_at : string option; [@json.option] [@json.drop_default]
    collection_ids : string array option; [@json.option] [@json.drop_default]
    rule_ids : string array option; [@json.option] [@json.drop_default]
    status_ids : string array option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let report_of_json = Report.of_json
let report_to_json = Report.to_json

module Notification = struct
  type t = {
    account : Account.t;
    created_at : string;
    id : string;
    type_ : NotificationTypeEnum.t; [@json.key "type"]
    event : RelationshipSeveranceEvent.t option; [@json.option] [@json.drop_default]
    fallback : NotificationFallback.t option; [@json.option] [@json.drop_default]
    group_key : string option; [@json.option] [@json.drop_default]
    moderation_warning : AccountWarning.t option; [@json.option] [@json.drop_default]
    report : Report.t option; [@json.option] [@json.drop_default]
    status : Status.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let notification_of_json = Notification.of_json
let notification_to_json = Notification.to_json

module NotificationPolicySummary = struct
  type t = {
    pending_notifications_count : int;
    pending_requests_count : int;
  } [@@deriving json]
end
let notificationPolicySummary_of_json = NotificationPolicySummary.of_json
let notificationPolicySummary_to_json = NotificationPolicySummary.to_json

module NotificationPolicy = struct
  type t = {
    for_limited_accounts : string;
    for_new_accounts : string;
    for_not_followers : string;
    for_not_following : string;
    for_private_mentions : string;
    summary : NotificationPolicySummary.t;
  } [@@deriving json]
end
let notificationPolicy_of_json = NotificationPolicy.of_json
let notificationPolicy_to_json = NotificationPolicy.to_json

module NotificationRequest = struct
  type t = {
    account : Account.t;
    created_at : string;
    id : string;
    notifications_count : string;
    updated_at : string;
    last_status : Status.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let notificationRequest_of_json = NotificationRequest.of_json
let notificationRequest_to_json = NotificationRequest.to_json

module PreferencesReadingExpandMediaEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module Preferences = struct
  type t = {
    posting_default_sensitive : bool; [@json.key "posting:default:sensitive"]
    posting_default_visibility : StatusVisibilityEnum.t; [@json.key "posting:default:visibility"]
    reading_expand_media : PreferencesReadingExpandMediaEnum.t; [@json.key "reading:expand:media"]
    reading_expand_spoilers : bool; [@json.key "reading:expand:spoilers"]
    posting_default_language : string option; [@json.key "posting:default:language"] [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let preferences_of_json = Preferences.of_json
let preferences_to_json = Preferences.to_json

module TrendsLink = struct
  type t = {
    description : string;
    embed_url : string;
    height : int;
    history : AdminEmailDomainBlockHistory.t array;
    html : string;
    provider_name : string;
    provider_url : string;
    title : string;
    type_ : TrendsLinkTypeEnum.t; [@json.key "type"]
    url : string;
    width : int;
    author_name : string option; [@json.option] [@json.drop_default]
    author_url : string option; [@json.option] [@json.drop_default]
    authors : PreviewCardAuthor.t array option; [@json.option] [@json.drop_default]
    blurhash : string option; [@json.option] [@json.drop_default]
    image : string option; [@json.option] [@json.drop_default]
    missing_attribution : bool option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let trendsLink_of_json = TrendsLink.of_json
let trendsLink_to_json = TrendsLink.to_json

module PrivacyPolicy = struct
  type t = {
    content : string;
    updated_at : string;
  } [@@deriving json]
end
let privacyPolicy_of_json = PrivacyPolicy.of_json
let privacyPolicy_to_json = PrivacyPolicy.to_json

module Profile = struct
  type t = {
    attribution_domains : string array;
    avatar_description : string;
    bot : bool;
    display_name : string;
    fields : Field.t array;
    header_description : string;
    id : string;
    indexable : bool;
    locked : bool;
    note : string;
    show_featured : bool;
    show_media : bool;
    show_media_replies : bool;
    avatar : string option; [@json.option] [@json.drop_default]
    avatar_static : string option; [@json.option] [@json.drop_default]
    discoverable : bool option; [@json.option] [@json.drop_default]
    header : string option; [@json.option] [@json.drop_default]
    header_static : string option; [@json.option] [@json.drop_default]
    hide_collections : bool option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let profile_of_json = Profile.of_json
let profile_to_json = Profile.to_json

module QuoteStateEnum = struct
  type t = string
  let of_json = Melange_json.Of_json.string
  let to_json = Melange_json.To_json.string
end

module Quote = struct
  type t = {
    state : QuoteStateEnum.t;
    quoted_status : Status.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let quote_of_json = Quote.of_json
let quote_to_json = Quote.to_json

module Relationship = struct
  type t = {
    blocked_by : bool;
    blocking : bool;
    domain_blocking : bool;
    endorsed : bool;
    followed_by : bool;
    following : bool;
    id : string;
    muting : bool;
    muting_notifications : bool;
    note : string;
    notifying : bool;
    requested : bool;
    requested_by : bool;
    showing_reblogs : bool;
    languages : string array option; [@json.option] [@json.drop_default]
    muting_expires_at : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let relationship_of_json = Relationship.of_json
let relationship_to_json = Relationship.to_json

module ScheduledStatusParamsPoll = struct
  type t = {
    options : string array;
    expires_in : int;
    multiple : bool;
    hide_totals : bool;
  } [@@deriving json]
end
let scheduledStatusParamsPoll_of_json = ScheduledStatusParamsPoll.of_json
let scheduledStatusParamsPoll_to_json = ScheduledStatusParamsPoll.to_json

module ScheduledStatusParams = struct
  type t = {
    application_id : int;
    text : string;
    visibility : StatusVisibilityEnum.t;
    with_rate_limit : bool;
    idempotency : string option; [@json.option] [@json.drop_default]
    in_reply_to_id : int option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    media_ids : string array option; [@json.option] [@json.drop_default]
    poll : ScheduledStatusParamsPoll.t option; [@json.option] [@json.drop_default]
    scheduled_at : string option; [@json.option] [@json.drop_default]
    sensitive : bool option; [@json.option] [@json.drop_default]
    spoiler_text : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let scheduledStatusParams_of_json = ScheduledStatusParams.of_json
let scheduledStatusParams_to_json = ScheduledStatusParams.to_json

module ScheduledStatus = struct
  type t = {
    id : string;
    media_attachments : MediaAttachment.t array;
    params : ScheduledStatusParams.t;
    scheduled_at : string;
  } [@@deriving json]
end
let scheduledStatus_of_json = ScheduledStatus.of_json
let scheduledStatus_to_json = ScheduledStatus.to_json

module TagHistory = struct
  type t = {
    accounts : string;
    day : string;
    uses : string;
  } [@@deriving json]
end
let tagHistory_of_json = TagHistory.of_json
let tagHistory_to_json = TagHistory.to_json

module Tag = struct
  type t = {
    history : TagHistory.t array;
    name : string;
    url : string;
    featuring : bool option; [@json.option] [@json.drop_default]
    following : bool option; [@json.option] [@json.drop_default]
    id : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let tag_of_json = Tag.of_json
let tag_to_json = Tag.to_json

module Search = struct
  type t = {
    accounts : Account.t array;
    hashtags : Tag.t array;
    statuses : Status.t array;
  } [@@deriving json]
end
let search_of_json = Search.of_json
let search_to_json = Search.to_json

module ShallowQuote = struct
  type t = {
    state : QuoteStateEnum.t;
    quoted_status_id : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let shallowQuote_of_json = ShallowQuote.of_json
let shallowQuote_to_json = ShallowQuote.to_json

module TranslationPollOption = struct
  type t = {
    title : string;
  } [@@deriving json]
end
let translationPollOption_of_json = TranslationPollOption.of_json
let translationPollOption_to_json = TranslationPollOption.to_json

module StatusEditPoll = struct
  type t = {
    options : TranslationPollOption.t array;
  } [@@deriving json]
end
let statusEditPoll_of_json = StatusEditPoll.of_json
let statusEditPoll_to_json = StatusEditPoll.to_json

module StatusEdit = struct
  type t = {
    account : Account.t;
    content : string;
    created_at : string;
    emojis : CustomEmoji.t array;
    media_attachments : MediaAttachment.t array;
    sensitive : bool;
    spoiler_text : string;
    poll : StatusEditPoll.t option; [@json.option] [@json.drop_default]
    quote : Melange_json.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let statusEdit_of_json = StatusEdit.of_json
let statusEdit_to_json = StatusEdit.to_json

module StatusSource = struct
  type t = {
    id : string;
    spoiler_text : string;
    text : string;
  } [@@deriving json]
end
let statusSource_of_json = StatusSource.of_json
let statusSource_to_json = StatusSource.to_json

module Suggestion = struct
  type t = {
    account : Account.t;
    sources : string array option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let suggestion_of_json = Suggestion.of_json
let suggestion_to_json = Suggestion.to_json

module AdminTag = struct
  type t = {
    requires_review : bool;
    trendable : bool;
    usable : bool;
  } [@@deriving json]
end
let adminTag_of_json = AdminTag.of_json
let adminTag_to_json = AdminTag.to_json

module TermsOfService = struct
  type t = {
    content : string;
    effective : bool;
    effective_date : string;
    succeeded_by : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let termsOfService_of_json = TermsOfService.of_json
let termsOfService_to_json = TermsOfService.to_json

module Token = struct
  type t = {
    access_token : string;
    created_at : float;
    scope : string;
    token_type : string;
  } [@@deriving json]
end
let token_of_json = Token.of_json
let token_to_json = Token.to_json

module TranslationAttachment = struct
  type t = {
    description : string;
    id : string;
  } [@@deriving json]
end
let translationAttachment_of_json = TranslationAttachment.of_json
let translationAttachment_to_json = TranslationAttachment.to_json

module TranslationPoll = struct
  type t = {
    id : string;
    options : TranslationPollOption.t array;
  } [@@deriving json]
end
let translationPoll_of_json = TranslationPoll.of_json
let translationPoll_to_json = TranslationPoll.to_json

module Translation = struct
  type t = {
    content : string;
    detected_source_language : string;
    language : string;
    media_attachments : TranslationAttachment.t array;
    provider : string;
    spoiler_text : string;
    poll : TranslationPoll.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let translation_of_json = Translation.of_json
let translation_to_json = Translation.to_json

module V1Filter = struct
  type t = {
    context : FilterContextEnum.t array;
    id : string;
    irreversible : bool;
    phrase : string;
    whole_word : bool;
    expires_at : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let v1Filter_of_json = V1Filter.of_json
let v1Filter_to_json = V1Filter.to_json

module V1InstanceConfigurationAccounts = struct
  type t = {
    max_featured_tags : int;
  } [@@deriving json]
end
let v1InstanceConfigurationAccounts_of_json = V1InstanceConfigurationAccounts.of_json
let v1InstanceConfigurationAccounts_to_json = V1InstanceConfigurationAccounts.to_json

module V1InstanceConfigurationMediaAttachments = struct
  type t = {
    image_matrix_limit : int;
    image_size_limit : int;
    supported_mime_types : string array;
    video_frame_rate_limit : int;
    video_matrix_limit : int;
    video_size_limit : int;
  } [@@deriving json]
end
let v1InstanceConfigurationMediaAttachments_of_json = V1InstanceConfigurationMediaAttachments.of_json
let v1InstanceConfigurationMediaAttachments_to_json = V1InstanceConfigurationMediaAttachments.to_json

module V1InstanceConfiguration = struct
  type t = {
    accounts : V1InstanceConfigurationAccounts.t;
    media_attachments : V1InstanceConfigurationMediaAttachments.t;
    polls : InstanceConfigurationPolls.t;
    statuses : InstanceConfigurationStatuses.t;
  } [@@deriving json]
end
let v1InstanceConfiguration_of_json = V1InstanceConfiguration.of_json
let v1InstanceConfiguration_to_json = V1InstanceConfiguration.to_json

module V1InstanceStats = struct
  type t = {
    domain_count : int;
    status_count : int;
    user_count : int;
  } [@@deriving json]
end
let v1InstanceStats_of_json = V1InstanceStats.of_json
let v1InstanceStats_to_json = V1InstanceStats.to_json

module V1InstanceUrls = struct
  type t = {
    streaming_api : string;
  } [@@deriving json]
end
let v1InstanceUrls_of_json = V1InstanceUrls.of_json
let v1InstanceUrls_to_json = V1InstanceUrls.to_json

module V1Instance = struct
  type t = {
    approval_required : bool;
    configuration : V1InstanceConfiguration.t;
    description : string;
    email : string;
    invites_enabled : bool;
    languages : string array;
    registrations : bool;
    rules : Rule.t array;
    short_description : string;
    stats : V1InstanceStats.t;
    title : string;
    uri : string;
    urls : V1InstanceUrls.t;
    version : string;
    contact_account : Account.t option; [@json.option] [@json.drop_default]
    thumbnail : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let v1Instance_of_json = V1Instance.of_json
let v1Instance_to_json = V1Instance.to_json

module V1NotificationPolicy = struct
  type t = {
    filter_new_accounts : bool;
    filter_not_followers : bool;
    filter_not_following : bool;
    filter_private_mentions : bool;
    summary : NotificationPolicySummary.t;
  } [@@deriving json]
end
let v1NotificationPolicy_of_json = V1NotificationPolicy.of_json
let v1NotificationPolicy_to_json = V1NotificationPolicy.to_json

module WebPushSubscriptionAlerts = struct
  type t = {
    admin_report : bool; [@json.key "admin.report"]
    admin_sign_up : bool; [@json.key "admin.sign_up"]
    favourite : bool;
    follow : bool;
    follow_request : bool;
    mention : bool;
    poll : bool;
    reblog : bool;
    status : bool;
    update : bool;
  } [@@deriving json]
end
let webPushSubscriptionAlerts_of_json = WebPushSubscriptionAlerts.of_json
let webPushSubscriptionAlerts_to_json = WebPushSubscriptionAlerts.to_json

module WebPushSubscription = struct
  type t = {
    alerts : WebPushSubscriptionAlerts.t;
    endpoint : string;
    id : string;
    server_key : string;
    standard : bool option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let webPushSubscription_of_json = WebPushSubscription.of_json
let webPushSubscription_to_json = WebPushSubscription.to_json

module NotificationGroup = struct
  type t = {
    group_key : string;
    most_recent_notification_id : int;
    notifications_count : int;
    sample_account_ids : string array;
    type_ : NotificationTypeEnum.t; [@json.key "type"]
    event : RelationshipSeveranceEvent.t option; [@json.option] [@json.drop_default]
    fallback : NotificationFallback.t option; [@json.option] [@json.drop_default]
    latest_page_notification_at : string option; [@json.option] [@json.drop_default]
    moderation_warning : AccountWarning.t option; [@json.option] [@json.drop_default]
    page_max_id : string option; [@json.option] [@json.drop_default]
    page_min_id : string option; [@json.option] [@json.drop_default]
    report : Report.t option; [@json.option] [@json.drop_default]
    status_id : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let notificationGroup_of_json = NotificationGroup.of_json
let notificationGroup_to_json = NotificationGroup.to_json

module GroupedNotificationsResults = struct
  type t = {
    accounts : Account.t array;
    notification_groups : NotificationGroup.t array;
    statuses : Status.t array;
    partial_accounts : PartialAccountWithAvatar.t array option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let groupedNotificationsResults_of_json = GroupedNotificationsResults.of_json
let groupedNotificationsResults_to_json = GroupedNotificationsResults.to_json

module DiscoverOauthServerConfigurationResponse = struct
  type t = {
    app_registration_endpoint : string;
    authorization_endpoint : string;
    code_challenge_methods_supported : string array;
    grant_types_supported : string array;
    issuer : string;
    response_modes_supported : string array;
    response_types_supported : string array;
    revocation_endpoint : string;
    scopes_supported : OAuthScopes.t;
    service_documentation : string;
    token_endpoint : string;
    token_endpoint_auth_methods_supported : string array;
    userinfo_endpoint : string;
  } [@@deriving json]
end
let discoverOauthServerConfigurationResponse_of_json = DiscoverOauthServerConfigurationResponse.of_json
let discoverOauthServerConfigurationResponse_to_json = DiscoverOauthServerConfigurationResponse.to_json

module OEmbedResponse = struct
  type t = {
    author_name : string;
    author_url : string;
    cache_age : int;
    html : string;
    provider_name : string;
    provider_url : string;
    title : string;
    type_ : string; [@json.key "type"]
    version : string;
    width : int;
    height : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let oEmbedResponse_of_json = OEmbedResponse.of_json
let oEmbedResponse_to_json = OEmbedResponse.to_json

module ValidationError = struct
  type t = {
    error : string;
    details : Melange_json.t;
  } [@@deriving json]
end
let validationError_of_json = ValidationError.of_json
let validationError_to_json = ValidationError.to_json

module AsyncRefreshResponse = struct
  type t = {
    async_refresh : AsyncRefresh.t;
  } [@@deriving json]
end
let asyncRefreshResponse_of_json = AsyncRefreshResponse.of_json
let asyncRefreshResponse_to_json = AsyncRefreshResponse.to_json

module CustomError422ErrorDetailsName = struct
  type t = {
    description : string;
    error : string;
  } [@@deriving json]
end
let customError422ErrorDetailsName_of_json = CustomError422ErrorDetailsName.of_json
let customError422ErrorDetailsName_to_json = CustomError422ErrorDetailsName.to_json

module CustomError422ErrorDetails = struct
  type t = {
    name : CustomError422ErrorDetailsName.t array;
  } [@@deriving json]
end
let customError422ErrorDetails_of_json = CustomError422ErrorDetails.of_json
let customError422ErrorDetails_to_json = CustomError422ErrorDetails.to_json

module CustomError422Error = struct
  type t = {
    details : CustomError422ErrorDetails.t;
    error : string;
  } [@@deriving json]
end
let customError422Error_of_json = CustomError422Error.of_json
let customError422Error_to_json = CustomError422Error.to_json

module CustomError422 = struct
  type t = {
    error : CustomError422Error.t;
  } [@@deriving json]
end
let customError422_of_json = CustomError422.of_json
let customError422_to_json = CustomError422.to_json

module CountResponse = struct
  type t = {
    count : int;
  } [@@deriving json]
end
let countResponse_of_json = CountResponse.of_json
let countResponse_to_json = CountResponse.to_json

module MergedResponse = struct
  type t = {
    merged : bool;
  } [@@deriving json]
end
let mergedResponse_of_json = MergedResponse.of_json
let mergedResponse_to_json = MergedResponse.to_json

module BaseStatus = struct
  type t = {
    in_reply_to_id : string option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    quote_approval_policy : string option; [@json.option] [@json.drop_default]
    quoted_status_id : string option; [@json.option] [@json.drop_default]
    scheduled_at : string option; [@json.option] [@json.drop_default]
    sensitive : bool option; [@json.option] [@json.drop_default]
    spoiler_text : string option; [@json.option] [@json.drop_default]
    visibility : StatusVisibilityEnum.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let baseStatus_of_json = BaseStatus.of_json
let baseStatus_to_json = BaseStatus.to_json

module TextStatus = struct
  type t = {
    in_reply_to_id : string option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    quote_approval_policy : string option; [@json.option] [@json.drop_default]
    quoted_status_id : string option; [@json.option] [@json.drop_default]
    scheduled_at : string option; [@json.option] [@json.drop_default]
    sensitive : bool option; [@json.option] [@json.drop_default]
    spoiler_text : string option; [@json.option] [@json.drop_default]
    visibility : StatusVisibilityEnum.t option; [@json.option] [@json.drop_default]
    status : string;
  } [@@deriving json]
end
let textStatus_of_json = TextStatus.of_json
let textStatus_to_json = TextStatus.to_json

module MediaStatus = struct
  type t = {
    in_reply_to_id : string option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    quote_approval_policy : string option; [@json.option] [@json.drop_default]
    quoted_status_id : string option; [@json.option] [@json.drop_default]
    scheduled_at : string option; [@json.option] [@json.drop_default]
    sensitive : bool option; [@json.option] [@json.drop_default]
    spoiler_text : string option; [@json.option] [@json.drop_default]
    visibility : StatusVisibilityEnum.t option; [@json.option] [@json.drop_default]
    media_ids : string array;
    status : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let mediaStatus_of_json = MediaStatus.of_json
let mediaStatus_to_json = MediaStatus.to_json

module PollStatusPoll = struct
  type t = {
    options : string array option; [@json.option] [@json.drop_default]
    expires_in : int option; [@json.option] [@json.drop_default]
    multiple : bool option; [@json.option] [@json.drop_default]
    hide_totals : bool option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let pollStatusPoll_of_json = PollStatusPoll.of_json
let pollStatusPoll_to_json = PollStatusPoll.to_json

module PollStatus = struct
  type t = {
    in_reply_to_id : string option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    quote_approval_policy : string option; [@json.option] [@json.drop_default]
    quoted_status_id : string option; [@json.option] [@json.drop_default]
    scheduled_at : string option; [@json.option] [@json.drop_default]
    sensitive : bool option; [@json.option] [@json.drop_default]
    spoiler_text : string option; [@json.option] [@json.drop_default]
    visibility : StatusVisibilityEnum.t option; [@json.option] [@json.drop_default]
    poll : PollStatusPoll.t;
    status : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let pollStatus_of_json = PollStatus.of_json
let pollStatus_to_json = PollStatus.to_json

module PatchAccountsUpdateCredentialsSource = struct
  type t = {
    privacy : StatusVisibilityEnum.t option; [@json.option] [@json.drop_default]
    sensitive : bool option; [@json.option] [@json.drop_default]
    language : string option; [@json.option] [@json.drop_default]
    quote_policy : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let patchAccountsUpdateCredentialsSource_of_json = PatchAccountsUpdateCredentialsSource.of_json
let patchAccountsUpdateCredentialsSource_to_json = PatchAccountsUpdateCredentialsSource.to_json

module CreateFilterV2KeywordsAttributes = struct
  type t = {
    keyword : string option; [@json.option] [@json.drop_default]
    whole_word : bool option; [@json.option] [@json.drop_default]
    id : string option; [@json.option] [@json.drop_default]
    _destroy : bool option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let createFilterV2KeywordsAttributes_of_json = CreateFilterV2KeywordsAttributes.of_json
let createFilterV2KeywordsAttributes_to_json = CreateFilterV2KeywordsAttributes.to_json

module GetInstanceActivityResponse = struct
  type t = {
    week : string option; [@json.option] [@json.drop_default]
    statuses : string option; [@json.option] [@json.drop_default]
    logins : string option; [@json.option] [@json.drop_default]
    registrations : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let getInstanceActivityResponse_of_json = GetInstanceActivityResponse.of_json
let getInstanceActivityResponse_to_json = GetInstanceActivityResponse.to_json

module CreateMarkerHome = struct
  type t = {
    last_read_id : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let createMarkerHome_of_json = CreateMarkerHome.of_json
let createMarkerHome_to_json = CreateMarkerHome.to_json

module CreatePushSubscriptionSubscriptionKeys = struct
  type t = {
    p256dh : string option; [@json.option] [@json.drop_default]
    auth : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let createPushSubscriptionSubscriptionKeys_of_json = CreatePushSubscriptionSubscriptionKeys.of_json
let createPushSubscriptionSubscriptionKeys_to_json = CreatePushSubscriptionSubscriptionKeys.to_json

module CreatePushSubscriptionSubscription = struct
  type t = {
    keys : CreatePushSubscriptionSubscriptionKeys.t option; [@json.option] [@json.drop_default]
    endpoint : string option; [@json.option] [@json.drop_default]
    standard : bool option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let createPushSubscriptionSubscription_of_json = CreatePushSubscriptionSubscription.of_json
let createPushSubscriptionSubscription_to_json = CreatePushSubscriptionSubscription.to_json

module CreatePushSubscriptionDataAlerts = struct
  type t = {
    mention : bool option; [@json.option] [@json.drop_default]
    quote : bool option; [@json.option] [@json.drop_default]
    status : bool option; [@json.option] [@json.drop_default]
    reblog : bool option; [@json.option] [@json.drop_default]
    follow : bool option; [@json.option] [@json.drop_default]
    follow_request : bool option; [@json.option] [@json.drop_default]
    favourite : bool option; [@json.option] [@json.drop_default]
    poll : bool option; [@json.option] [@json.drop_default]
    update : bool option; [@json.option] [@json.drop_default]
    quoted_update : bool option; [@json.option] [@json.drop_default]
    admin_sign_up : bool option; [@json.key "admin.sign_up"] [@json.option] [@json.drop_default]
    admin_report : bool option; [@json.key "admin.report"] [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let createPushSubscriptionDataAlerts_of_json = CreatePushSubscriptionDataAlerts.of_json
let createPushSubscriptionDataAlerts_to_json = CreatePushSubscriptionDataAlerts.to_json

module CreatePushSubscriptionData = struct
  type t = {
    alerts : CreatePushSubscriptionDataAlerts.t option; [@json.option] [@json.drop_default]
    policy : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let createPushSubscriptionData_of_json = CreatePushSubscriptionData.of_json
let createPushSubscriptionData_to_json = CreatePushSubscriptionData.to_json

module PutPushSubscriptionDataAlerts = struct
  type t = {
    mention : bool option; [@json.option] [@json.drop_default]
    status : bool option; [@json.option] [@json.drop_default]
    reblog : bool option; [@json.option] [@json.drop_default]
    follow : bool option; [@json.option] [@json.drop_default]
    follow_request : bool option; [@json.option] [@json.drop_default]
    favourite : bool option; [@json.option] [@json.drop_default]
    poll : bool option; [@json.option] [@json.drop_default]
    update : bool option; [@json.option] [@json.drop_default]
    admin_sign_up : bool option; [@json.key "admin.sign_up"] [@json.option] [@json.drop_default]
    admin_report : bool option; [@json.key "admin.report"] [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let putPushSubscriptionDataAlerts_of_json = PutPushSubscriptionDataAlerts.of_json
let putPushSubscriptionDataAlerts_to_json = PutPushSubscriptionDataAlerts.to_json

module PutPushSubscriptionData = struct
  type t = {
    alerts : PutPushSubscriptionDataAlerts.t option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let putPushSubscriptionData_of_json = PutPushSubscriptionData.of_json
let putPushSubscriptionData_to_json = PutPushSubscriptionData.to_json

