// API endpoints (ReScript type layer).
// Generated by melange-jsdoc-gen. DO NOT EDIT.
// send delegates encode/decode to the Melange layer; inject fetch for transport.

type fetchFn = (string, string, JSON.t) => promise<JSON.t>

module Graphql = {
  module AccountByUsername = {
    type request = {
      username: string,
    }
    type response = ComponentSchemas.AccountByUsernameResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "accountByUsername_send"
  }

  module ActorByHandle = {
    type request = {
      handle: string,
      allowLocalHandle?: bool,
    }
    type response = ComponentSchemas.ActorByHandleResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "actorByHandle_send"
  }

  module ActorPosts = {
    type request = {
      handle: string,
      after?: string,
      first?: int,
    }
    type response = ComponentSchemas.ActorPostsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "actorPosts_send"
  }

  module ActorPostsById = {
    type request = {
      id: string,
      after?: string,
      first?: int,
    }
    type response = ComponentSchemas.ActorPostsByIdResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "actorPostsById_send"
  }

  module AddReaction = {
    type request = {
      input: ComponentSchemas.AddReactionToPostInput.t,
    }
    type response = ComponentSchemas.AddReactionResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "addReaction_send"
  }

  module BookmarkPost = {
    type request = {
      input: ComponentSchemas.BookmarkPostInput.t,
    }
    type response = ComponentSchemas.BookmarkPostResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "bookmarkPost_send"
  }

  module CompleteLoginChallenge = {
    type request = {
      token: string,
      code: string,
    }
    type response = ComponentSchemas.CompleteLoginChallengeResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "completeLoginChallenge_send"
  }

  module CreateMedium = {
    type request = {
      input: ComponentSchemas.CreateMediumInput.t,
    }
    type response = ComponentSchemas.CreateMediumResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createMedium_send"
  }

  module CreateNote = {
    type request = {
      input: ComponentSchemas.CreateNoteInput.t,
    }
    type response = ComponentSchemas.CreateNoteResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createNote_send"
  }

  module DeletePost = {
    type request = {
      input: ComponentSchemas.DeletePostInput.t,
    }
    type response = ComponentSchemas.DeletePostResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deletePost_send"
  }

  module FinishMediumUpload = {
    type request = {
      input: ComponentSchemas.FinishMediumUploadInput.t,
    }
    type response = ComponentSchemas.FinishMediumUploadResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "finishMediumUpload_send"
  }

  module FollowActor = {
    type request = {
      input: ComponentSchemas.FollowActorInput.t,
    }
    type response = ComponentSchemas.FollowActorResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "followActor_send"
  }

  module LoginByEmail = {
    type request = {
      email: string,
      locale: string,
      verifyUrl: string,
    }
    type response = ComponentSchemas.LoginByEmailResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "loginByEmail_send"
  }

  module LoginByUsername = {
    type request = {
      username: string,
      locale: string,
      verifyUrl: string,
    }
    type response = ComponentSchemas.LoginByUsernameResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "loginByUsername_send"
  }

  module MarkNotificationsAsRead = {
    type request = {
      upTo?: string,
    }
    type response = ComponentSchemas.MarkNotificationsAsReadResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "markNotificationsAsRead_send"
  }

  module Notifications = {
    type request = {
      after?: string,
      first?: int,
    }
    type response = ComponentSchemas.NotificationsResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "notifications_send"
  }

  module PersonalTimeline = {
    type request = {
      after?: string,
      first?: int,
      languages?: array<string>,
      withoutShares?: bool,
    }
    type response = ComponentSchemas.PersonalTimelineResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "personalTimeline_send"
  }

  module PostById = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.PostByIdResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postById_send"
  }

  module PostByUrl = {
    type request = {
      url: string,
    }
    type response = ComponentSchemas.PostByUrlResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postByUrl_send"
  }

  module PostReplies = {
    type request = {
      id: string,
      after?: string,
      first?: int,
    }
    type response = ComponentSchemas.PostRepliesResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postReplies_send"
  }

  module PublicTimeline = {
    type request = {
      after?: string,
      first?: int,
      languages?: array<string>,
      withoutShares?: bool,
    }
    type response = ComponentSchemas.PublicTimelineResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "publicTimeline_send"
  }

  module RemoveReaction = {
    type request = {
      input: ComponentSchemas.RemoveReactionFromPostInput.t,
    }
    type response = ComponentSchemas.RemoveReactionResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "removeReaction_send"
  }

  module SharePost = {
    type request = {
      input: ComponentSchemas.SharePostInput.t,
    }
    type response = ComponentSchemas.SharePostResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "sharePost_send"
  }

  module StartMediumUpload = {
    type request = {
      input: ComponentSchemas.StartMediumUploadInput.t,
    }
    type response = ComponentSchemas.StartMediumUploadResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "startMediumUpload_send"
  }

  module UnbookmarkPost = {
    type request = {
      input: ComponentSchemas.UnbookmarkPostInput.t,
    }
    type response = ComponentSchemas.UnbookmarkPostResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "unbookmarkPost_send"
  }

  module UnfollowActor = {
    type request = {
      input: ComponentSchemas.UnfollowActorInput.t,
    }
    type response = ComponentSchemas.UnfollowActorResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "unfollowActor_send"
  }

  module UnsharePost = {
    type request = {
      input: ComponentSchemas.UnsharePostInput.t,
    }
    type response = ComponentSchemas.UnsharePostResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "unsharePost_send"
  }

  module UpdateNote = {
    type request = {
      input: ComponentSchemas.UpdateNoteInput.t,
    }
    type response = ComponentSchemas.UpdateNoteResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateNote_send"
  }

  module Viewer = {
    type request = unit
    type response = ComponentSchemas.ViewerResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "viewer_send"
  }

  module VoteOnPoll = {
    type request = {
      input: ComponentSchemas.VoteOnPollInput.t,
    }
    type response = ComponentSchemas.VoteOnPollResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "voteOnPoll_send"
  }

}

