(* Generated by the OCaml generator. Do not edit. *)
open! Melange_json.Primitives

module PublicTimelineDataPublicTimelineEdgesNodeActor = struct
  type t = {
    handle : string;
    name : string option; [@json.option] [@json.drop_default]
    avatarUrl : string;
  } [@@deriving json]
end
let publicTimelineDataPublicTimelineEdgesNodeActor_of_json = PublicTimelineDataPublicTimelineEdgesNodeActor.of_json
let publicTimelineDataPublicTimelineEdgesNodeActor_to_json = PublicTimelineDataPublicTimelineEdgesNodeActor.to_json

module PublicTimelineDataPublicTimelineEdgesNode = struct
  type t = {
    id : string;
    content : string;
    excerpt : string;
    language : string option; [@json.option] [@json.drop_default]
    published : string;
    actor : PublicTimelineDataPublicTimelineEdgesNodeActor.t;
  } [@@deriving json]
end
let publicTimelineDataPublicTimelineEdgesNode_of_json = PublicTimelineDataPublicTimelineEdgesNode.of_json
let publicTimelineDataPublicTimelineEdgesNode_to_json = PublicTimelineDataPublicTimelineEdgesNode.to_json

module PublicTimelineDataPublicTimelineEdges = struct
  type t = {
    cursor : string;
    node : PublicTimelineDataPublicTimelineEdgesNode.t;
  } [@@deriving json]
end
let publicTimelineDataPublicTimelineEdges_of_json = PublicTimelineDataPublicTimelineEdges.of_json
let publicTimelineDataPublicTimelineEdges_to_json = PublicTimelineDataPublicTimelineEdges.to_json

module PublicTimelineDataPublicTimelinePageInfo = struct
  type t = {
    endCursor : string option; [@json.option] [@json.drop_default]
    hasNextPage : bool;
  } [@@deriving json]
end
let publicTimelineDataPublicTimelinePageInfo_of_json = PublicTimelineDataPublicTimelinePageInfo.of_json
let publicTimelineDataPublicTimelinePageInfo_to_json = PublicTimelineDataPublicTimelinePageInfo.to_json

module PublicTimelineDataPublicTimeline = struct
  type t = {
    edges : PublicTimelineDataPublicTimelineEdges.t array;
    pageInfo : PublicTimelineDataPublicTimelinePageInfo.t;
  } [@@deriving json]
end
let publicTimelineDataPublicTimeline_of_json = PublicTimelineDataPublicTimeline.of_json
let publicTimelineDataPublicTimeline_to_json = PublicTimelineDataPublicTimeline.to_json

module PublicTimelineData = struct
  type t = {
    publicTimeline : PublicTimelineDataPublicTimeline.t;
  } [@@deriving json]
end
let publicTimelineData_of_json = PublicTimelineData.of_json
let publicTimelineData_to_json = PublicTimelineData.to_json

module PublicTimelineResponse = struct
  type t = {
    data : PublicTimelineData.t;
  } [@@deriving json]
end
let publicTimelineResponse_of_json = PublicTimelineResponse.of_json
let publicTimelineResponse_to_json = PublicTimelineResponse.to_json

