(* Generated by the OCaml generator. Do not edit. *)
open! Melange_json.Primitives
open ComponentSchemas

module PublicTimeline = struct
  type request = {
    after : string option; [@json.option] [@json.drop_default]
  } [@@deriving json]
end
let publicTimeline_send (fetch : string -> string -> Js.Json.t -> Js.Json.t Js.Promise.t) (req : PublicTimeline.request) =
  let variables = PublicTimeline.request_to_json req in
  let body = Js.Json.object_ (Js.Dict.fromList [("query", Js.Json.string "query PublicTimeline($after: String) {\n  publicTimeline(after: $after) {\n    edges {\n      cursor\n      node {\n        id\n        content\n        excerpt\n        language\n        published\n        actor {\n          handle\n          name\n          avatarUrl\n        }\n      }\n    }\n    pageInfo {\n      endCursor\n      hasNextPage\n    }\n  }\n}"); ("variables", variables)]) in
  Js.Promise.then_ (fun j -> Js.Promise.resolve (PublicTimelineResponse.of_json j)) (fetch "POST" "/graphql" body)

