// Shared component schemas (ReScript type layer).
// Generated by melange-jsdoc-gen. DO NOT EDIT.
// Types are plain records; encode/decode delegates to the Melange layer.

module OAuthScope = {
  type t = string
}

module OAuthScopes = {
  type t = array<OAuthScope.t>
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "oAuthScopes_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "oAuthScopes_to_json"
}

module AccountRole = {
  type t = {
    color: string,
    id: string,
    name: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "accountRole_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "accountRole_to_json"
}

module CustomEmoji = {
  type t = {
    shortcode: string,
    static_url: string,
    url: string,
    visible_in_picker: bool,
    category?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "customEmoji_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "customEmoji_to_json"
}

module FeatureApprovalAutomaticEnum = {
  type t = string
}

module FeatureApprovalCurrentUserEnum = {
  type t = string
}

module QuoteApprovalAutomaticEnum = {
  type t = string
}

module FeatureApproval = {
  type t = {
    automatic: array<FeatureApprovalAutomaticEnum.t>,
    current_user: FeatureApprovalCurrentUserEnum.t,
    manual: array<QuoteApprovalAutomaticEnum.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "featureApproval_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "featureApproval_to_json"
}

module Field = {
  type t = {
    name: string,
    value: string,
    verified_at?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "field_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "field_to_json"
}

module Account = {
  type rec t = {
    acct: string,
    avatar: string,
    avatar_static: string,
    bot: bool,
    created_at: string,
    display_name: string,
    emojis: array<CustomEmoji.t>,
    fields: array<Field.t>,
    followers_count: int,
    following_count: int,
    group: bool,
    header: string,
    header_static: string,
    id: string,
    locked: bool,
    note: string,
    statuses_count: int,
    uri: string,
    username: string,
    avatar_description?: string,
    discoverable?: bool,
    feature_approval?: FeatureApproval.t,
    header_description?: string,
    hide_collections?: bool,
    indexable?: bool,
    last_status_at?: string,
    limited?: bool,
    memorial?: bool,
    moved?: t,
    noindex?: bool,
    roles?: array<AccountRole.t>,
    show_featured?: bool,
    show_media?: bool,
    show_media_replies?: bool,
    suspended?: bool,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "account_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "account_to_json"
}

module CredentialAccountSourceQuotePolicyEnum = {
  type t = string
}

module StatusVisibilityEnum = {
  type t = string
}

module CredentialAccountSource = {
  type t = {
    fields: array<Field.t>,
    follow_requests_count: int,
    note: string,
    privacy: StatusVisibilityEnum.t,
    sensitive: bool,
    attribution_domains?: array<string>,
    discoverable?: bool,
    hide_collections?: bool,
    indexable?: bool,
    language?: string,
    quote_policy?: CredentialAccountSourceQuotePolicyEnum.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "credentialAccountSource_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "credentialAccountSource_to_json"
}

module Role = {
  type t = {
    color: string,
    highlighted: bool,
    id: string,
    name: string,
    permissions: string,
    collection_limit?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "role_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "role_to_json"
}

module CredentialAccount = {
  type t = {
    acct: string,
    avatar: string,
    avatar_static: string,
    bot: bool,
    created_at: string,
    display_name: string,
    emojis: array<CustomEmoji.t>,
    fields: array<Field.t>,
    followers_count: int,
    following_count: int,
    group: bool,
    header: string,
    header_static: string,
    id: string,
    locked: bool,
    note: string,
    role: Role.t,
    source: CredentialAccountSource.t,
    statuses_count: int,
    uri: string,
    username: string,
    avatar_description?: string,
    discoverable?: bool,
    feature_approval?: FeatureApproval.t,
    header_description?: string,
    hide_collections?: bool,
    indexable?: bool,
    last_status_at?: string,
    limited?: bool,
    memorial?: bool,
    moved?: Account.t,
    noindex?: bool,
    roles?: array<AccountRole.t>,
    show_featured?: bool,
    show_media?: bool,
    show_media_replies?: bool,
    suspended?: bool,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "credentialAccount_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "credentialAccount_to_json"
}

module MutedAccount = {
  type t = {
    acct: string,
    avatar: string,
    avatar_static: string,
    bot: bool,
    created_at: string,
    display_name: string,
    emojis: array<CustomEmoji.t>,
    fields: array<Field.t>,
    followers_count: int,
    following_count: int,
    group: bool,
    header: string,
    header_static: string,
    id: string,
    locked: bool,
    note: string,
    statuses_count: int,
    uri: string,
    username: string,
    avatar_description?: string,
    discoverable?: bool,
    feature_approval?: FeatureApproval.t,
    header_description?: string,
    hide_collections?: bool,
    indexable?: bool,
    last_status_at?: string,
    limited?: bool,
    memorial?: bool,
    moved?: Account.t,
    mute_expires_at?: string,
    noindex?: bool,
    roles?: array<AccountRole.t>,
    show_featured?: bool,
    show_media?: bool,
    show_media_replies?: bool,
    suspended?: bool,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "mutedAccount_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "mutedAccount_to_json"
}

module PartialAccountWithAvatar = {
  type t = {
    acct?: string,
    avatar?: string,
    avatar_description?: string,
    avatar_static?: string,
    bot?: bool,
    id?: string,
    locked?: bool,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "partialAccountWithAvatar_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "partialAccountWithAvatar_to_json"
}

module AccountWarningActionEnum = {
  type t = string
}

module AppealStateEnum = {
  type t = string
}

module Appeal = {
  type t = {
    state: AppealStateEnum.t,
    text: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "appeal_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "appeal_to_json"
}

module AccountWarning = {
  type t = {
    action: AccountWarningActionEnum.t,
    created_at: string,
    id: string,
    target_account: Account.t,
    text: string,
    appeal?: Appeal.t,
    status_ids?: array<string>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "accountWarning_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "accountWarning_to_json"
}

module AdminIp = {
  type t = {
    ip: string,
    used_at: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminIp_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminIp_to_json"
}

module AdminAccount = {
  type t = {
    account: Account.t,
    approved: bool,
    confirmed: bool,
    created_at: string,
    disabled: bool,
    email: string,
    id: string,
    ips: array<AdminIp.t>,
    locale: string,
    role: Role.t,
    sensitized: bool,
    silenced: bool,
    suspended: bool,
    username: string,
    created_by_application_id?: string,
    domain?: string,
    invite_request?: string,
    invited_by_account_id?: string,
    ip?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminAccount_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminAccount_to_json"
}

module AdminCanonicalEmailBlock = {
  type t = {
    canonical_email_hash: string,
    id: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminCanonicalEmailBlock_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminCanonicalEmailBlock_to_json"
}

module AdminCohortFrequencyEnum = {
  type t = string
}

module CohortData = {
  type t = {
    date: string,
    rate: float,
    value: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "cohortData_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "cohortData_to_json"
}

module AdminCohort = {
  type t = {
    data: array<CohortData.t>,
    frequency: AdminCohortFrequencyEnum.t,
    period: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminCohort_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminCohort_to_json"
}

module AdminDimensionData = {
  type t = {
    human_key: string,
    key: string,
    value: string,
    human_value?: string,
    unit?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminDimensionData_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminDimensionData_to_json"
}

module AdminDimension = {
  type t = {
    data: array<AdminDimensionData.t>,
    key: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminDimension_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminDimension_to_json"
}

module AdminDomainAllow = {
  type t = {
    created_at: string,
    domain: string,
    id: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminDomainAllow_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminDomainAllow_to_json"
}

module AdminDomainBlockSeverityEnum = {
  type t = string
}

module AdminDomainBlock = {
  type t = {
    created_at: string,
    domain: string,
    id: string,
    obfuscate: bool,
    reject_media: bool,
    reject_reports: bool,
    severity: AdminDomainBlockSeverityEnum.t,
    digest?: string,
    private_comment?: string,
    public_comment?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminDomainBlock_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminDomainBlock_to_json"
}

module AdminEmailDomainBlockHistory = {
  type t = {
    accounts: string,
    day: string,
    uses: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminEmailDomainBlockHistory_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminEmailDomainBlockHistory_to_json"
}

module AdminEmailDomainBlock = {
  type t = {
    created_at: string,
    domain: string,
    history: array<AdminEmailDomainBlockHistory.t>,
    id: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminEmailDomainBlock_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminEmailDomainBlock_to_json"
}

module AdminIpBlockSeverityEnum = {
  type t = string
}

module AdminIpBlock = {
  type t = {
    comment: string,
    created_at: string,
    id: string,
    ip: string,
    severity: AdminIpBlockSeverityEnum.t,
    expires_at?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminIpBlock_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminIpBlock_to_json"
}

module AdminMeasureData = {
  type t = {
    date: string,
    value: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminMeasureData_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminMeasureData_to_json"
}

module AdminMeasure = {
  type t = {
    data: array<AdminMeasureData.t>,
    key: string,
    total: string,
    human_value?: string,
    previous_total?: string,
    unit?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminMeasure_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminMeasure_to_json"
}

module ReportCategoryEnum = {
  type t = string
}

module Rule = {
  type t = {
    id: string,
    text: string,
    hint?: string,
    translations?: JSON.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "rule_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "rule_to_json"
}

module CollectionItemStateEnum = {
  type t = string
}

module CollectionItem = {
  type t = {
    created_at: string,
    id: string,
    state: CollectionItemStateEnum.t,
    account_id?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "collectionItem_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "collectionItem_to_json"
}

module ShallowTag = {
  type t = {
    name: string,
    url: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "shallowTag_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "shallowTag_to_json"
}

module Collection = {
  type t = {
    account_id: string,
    created_at: string,
    description: string,
    discoverable: bool,
    id: string,
    item_count: int,
    items: array<CollectionItem.t>,
    local: bool,
    name: string,
    sensitive: bool,
    updated_at: string,
    uri: string,
    language?: string,
    tag?: ShallowTag.t,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "collection_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "collection_to_json"
}

module FilterContextEnum = {
  type t = string
}

module FilterFilterActionEnum = {
  type t = string
}

module FilterKeyword = {
  type t = {
    id: string,
    keyword: string,
    whole_word: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "filterKeyword_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "filterKeyword_to_json"
}

module FilterStatus = {
  type t = {
    id: string,
    status_id: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "filterStatus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "filterStatus_to_json"
}

module Filter = {
  type t = {
    context: array<FilterContextEnum.t>,
    filter_action: FilterFilterActionEnum.t,
    id: string,
    title: string,
    expires_at?: string,
    keywords?: array<FilterKeyword.t>,
    statuses?: array<FilterStatus.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "filter_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "filter_to_json"
}

module FilterResult = {
  type t = {
    filter: Filter.t,
    keyword_matches?: array<string>,
    status_matches?: array<string>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "filterResult_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "filterResult_to_json"
}

module MediaAttachmentMetaFocus = {
  type t = {
    x?: float,
    y?: float,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "mediaAttachmentMetaFocus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "mediaAttachmentMetaFocus_to_json"
}

module MetaDetails = {
  type t = {
    aspect?: float,
    bitrate?: int,
    duration?: float,
    frame_rate?: string,
    height?: int,
    width?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "metaDetails_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "metaDetails_to_json"
}

module MediaAttachmentMeta = {
  type t = {
    small?: MetaDetails.t,
    original?: MetaDetails.t,
    focus?: MediaAttachmentMetaFocus.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "mediaAttachmentMeta_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "mediaAttachmentMeta_to_json"
}

module MediaAttachmentTypeEnum = {
  type t = string
}

module MediaAttachment = {
  type t = {
    id: string,
    @as("type") type_: MediaAttachmentTypeEnum.t,
    blurhash?: string,
    description?: string,
    meta?: MediaAttachmentMeta.t,
    preview_url?: string,
    remote_url?: string,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "mediaAttachment_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "mediaAttachment_to_json"
}

module PollOption = {
  type t = {
    title: string,
    votes_count?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "pollOption_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "pollOption_to_json"
}

module Poll = {
  type t = {
    emojis: array<CustomEmoji.t>,
    expired: bool,
    id: string,
    multiple: bool,
    options: array<PollOption.t>,
    votes_count: int,
    expires_at?: string,
    own_votes?: array<int>,
    voted?: bool,
    voters_count?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "poll_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "poll_to_json"
}

module PreviewCardAuthor = {
  type t = {
    name: string,
    url: string,
    account?: Account.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "previewCardAuthor_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "previewCardAuthor_to_json"
}

module TrendsLinkTypeEnum = {
  type t = string
}

module PreviewCard = {
  type t = {
    description: string,
    embed_url: string,
    height: int,
    html: string,
    provider_name: string,
    provider_url: string,
    title: string,
    @as("type") type_: TrendsLinkTypeEnum.t,
    url: string,
    width: int,
    author_name?: string,
    author_url?: string,
    authors?: array<PreviewCardAuthor.t>,
    blurhash?: string,
    image?: string,
    missing_attribution?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "previewCard_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "previewCard_to_json"
}

module QuoteApprovalCurrentUserEnum = {
  type t = string
}

module QuoteApproval = {
  type t = {
    automatic: array<QuoteApprovalAutomaticEnum.t>,
    current_user: QuoteApprovalCurrentUserEnum.t,
    manual: array<QuoteApprovalAutomaticEnum.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "quoteApproval_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "quoteApproval_to_json"
}

module StatusApplication = {
  type t = {
    name: string,
    website?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "statusApplication_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "statusApplication_to_json"
}

module StatusMention = {
  type t = {
    acct: string,
    id: string,
    url: string,
    username: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "statusMention_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "statusMention_to_json"
}

module StatusTag = {
  type t = {
    name: string,
    url: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "statusTag_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "statusTag_to_json"
}

module Status = {
  type rec t = {
    account: Account.t,
    content: string,
    created_at: string,
    emojis: array<CustomEmoji.t>,
    favourites_count: int,
    id: string,
    media_attachments: array<MediaAttachment.t>,
    mentions: array<StatusMention.t>,
    reblogs_count: int,
    replies_count: int,
    sensitive: bool,
    spoiler_text: string,
    tags: array<StatusTag.t>,
    uri: string,
    visibility: StatusVisibilityEnum.t,
    application?: StatusApplication.t,
    bookmarked?: bool,
    card?: PreviewCard.t,
    edited_at?: string,
    favourited?: bool,
    filtered?: array<FilterResult.t>,
    in_reply_to_account_id?: string,
    in_reply_to_id?: string,
    language?: string,
    muted?: bool,
    pinned?: bool,
    poll?: Poll.t,
    quote?: JSON.t,
    quote_approval?: QuoteApproval.t,
    quotes_count?: int,
    reblog?: t,
    reblogged?: bool,
    tagged_collections?: array<Collection.t>,
    text?: string,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "status_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "status_to_json"
}

module AdminReport = {
  type t = {
    account: AdminAccount.t,
    action_taken: bool,
    category: ReportCategoryEnum.t,
    comment: string,
    created_at: string,
    forwarded: bool,
    id: string,
    rules: array<Rule.t>,
    statuses: array<Status.t>,
    target_account: AdminAccount.t,
    updated_at: string,
    action_taken_at?: string,
    action_taken_by_account?: AdminAccount.t,
    assigned_account?: AdminAccount.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminReport_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminReport_to_json"
}

module AnnouncementAccount = {
  type t = {
    acct: string,
    id: string,
    url: string,
    username: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "announcementAccount_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "announcementAccount_to_json"
}

module AnnouncementStatus = {
  type t = {
    id: string,
    url: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "announcementStatus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "announcementStatus_to_json"
}

module Reaction = {
  type t = {
    count: int,
    name: string,
    me?: bool,
    static_url?: string,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "reaction_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "reaction_to_json"
}

module Announcement = {
  type t = {
    all_day: bool,
    content: string,
    emojis: array<CustomEmoji.t>,
    id: string,
    mentions: array<AnnouncementAccount.t>,
    published_at: string,
    reactions: array<Reaction.t>,
    statuses: array<AnnouncementStatus.t>,
    tags: array<StatusTag.t>,
    updated_at: string,
    ends_at?: string,
    read?: bool,
    starts_at?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "announcement_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "announcement_to_json"
}

module AnnualReportData = {
  type t = {
    archetype?: string,
    type_distribution?: JSON.t,
    top_statuses?: JSON.t,
    most_used_apps?: array<JSON.t>,
    commonly_interacted_with_accounts?: array<JSON.t>,
    time_series?: array<JSON.t>,
    top_hashtags?: array<JSON.t>,
    most_reblogged_accounts?: array<JSON.t>,
    percentiles?: float,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "annualReportData_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "annualReportData_to_json"
}

module AnnualReport = {
  type t = {
    account_id?: string,
    data?: AnnualReportData.t,
    schema_version?: int,
    share_url?: string,
    year?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "annualReport_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "annualReport_to_json"
}

module Application = {
  type t = {
    id: string,
    name: string,
    redirect_uri?: string,
    redirect_uris?: array<string>,
    scopes?: OAuthScopes.t,
    vapid_key?: string,
    website?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "application_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "application_to_json"
}

module CredentialApplication = {
  type t = {
    client_id: string,
    client_secret: string,
    id: string,
    name: string,
    client_secret_expires_at?: int,
    redirect_uri?: string,
    redirect_uris?: array<string>,
    scopes?: OAuthScopes.t,
    vapid_key?: string,
    website?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "credentialApplication_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "credentialApplication_to_json"
}

module AsyncRefreshStatusEnum = {
  type t = string
}

module AsyncRefresh = {
  type t = {
    id: string,
    status: AsyncRefreshStatusEnum.t,
    result_count?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "asyncRefresh_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "asyncRefresh_to_json"
}

module CollectionWithAccounts = {
  type t = {
    accounts: array<Account.t>,
    collection: Collection.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "collectionWithAccounts_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "collectionWithAccounts_to_json"
}

module Context = {
  type t = {
    ancestors: array<Status.t>,
    descendants: array<Status.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "context_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "context_to_json"
}

module Conversation = {
  type t = {
    accounts: array<Account.t>,
    id: string,
    unread: bool,
    last_status?: Status.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "conversation_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "conversation_to_json"
}

module DomainBlockSeverityEnum = {
  type t = string
}

module DomainBlock = {
  type t = {
    digest: string,
    domain: string,
    severity: DomainBlockSeverityEnum.t,
    comment?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "domainBlock_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "domainBlock_to_json"
}

module Error = {
  type t = {
    error: string,
    error_description?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "error_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "error_to_json"
}

module ExtendedDescription = {
  type t = {
    content: string,
    updated_at: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "extendedDescription_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "extendedDescription_to_json"
}

module FamiliarFollowers = {
  type t = {
    accounts: array<Account.t>,
    id: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "familiarFollowers_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "familiarFollowers_to_json"
}

module FeaturedTag = {
  type t = {
    id: string,
    name: string,
    statuses_count: string,
    url: string,
    last_status_at?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "featuredTag_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "featuredTag_to_json"
}

module IdentityProof = {
  type t = {
    profile_url: string,
    proof_url: string,
    provider: string,
    provider_username: string,
    updated_at: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "identityProof_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "identityProof_to_json"
}

module InstanceApiVersions = {
  type t = {
    mastodon?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceApiVersions_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceApiVersions_to_json"
}

module InstanceConfigurationAccounts = {
  type t = {
    max_featured_tags: int,
    max_display_name_length?: int,
    max_note_length?: int,
    max_pinned_statuses?: int,
    max_profile_fields?: int,
    profile_field_name_limit?: int,
    profile_field_value_limit?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationAccounts_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationAccounts_to_json"
}

module InstanceConfigurationMediaAttachments = {
  type t = {
    image_matrix_limit: int,
    image_size_limit: int,
    supported_mime_types: array<string>,
    video_frame_rate_limit: int,
    video_matrix_limit: int,
    video_size_limit: int,
    description_limit?: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationMediaAttachments_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationMediaAttachments_to_json"
}

module InstanceConfigurationPolls = {
  type t = {
    max_characters_per_option: int,
    max_expiration: int,
    max_options: int,
    min_expiration: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationPolls_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationPolls_to_json"
}

module InstanceConfigurationStatuses = {
  type t = {
    characters_reserved_per_url: int,
    max_characters: int,
    max_media_attachments: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationStatuses_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationStatuses_to_json"
}

module InstanceConfigurationTimelinesAccessHashtagFeeds = {
  type t = {
    local?: string,
    remote?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationTimelinesAccessHashtagFeeds_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationTimelinesAccessHashtagFeeds_to_json"
}

module InstanceConfigurationTimelinesAccessLiveFeeds = {
  type t = {
    local?: string,
    remote?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationTimelinesAccessLiveFeeds_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationTimelinesAccessLiveFeeds_to_json"
}

module InstanceConfigurationTimelinesAccess = {
  type t = {
    live_feeds?: InstanceConfigurationTimelinesAccessLiveFeeds.t,
    hashtag_feeds?: InstanceConfigurationTimelinesAccessHashtagFeeds.t,
    trending_link_feeds?: InstanceConfigurationTimelinesAccessHashtagFeeds.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationTimelinesAccess_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationTimelinesAccess_to_json"
}

module InstanceConfigurationTranslation = {
  type t = {
    enabled: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationTranslation_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationTranslation_to_json"
}

module InstanceConfigurationUrls = {
  type t = {
    about?: string,
    privacy_policy?: string,
    status?: string,
    streaming?: string,
    terms_of_service?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfigurationUrls_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfigurationUrls_to_json"
}

module InstanceConfiguration = {
  type t = {
    accounts: InstanceConfigurationAccounts.t,
    media_attachments: InstanceConfigurationMediaAttachments.t,
    polls: InstanceConfigurationPolls.t,
    statuses: InstanceConfigurationStatuses.t,
    translation: InstanceConfigurationTranslation.t,
    urls: InstanceConfigurationUrls.t,
    limited_federation?: bool,
    timelines_access?: InstanceConfigurationTimelinesAccess.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceConfiguration_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceConfiguration_to_json"
}

module InstanceContact = {
  type t = {
    email: string,
    account?: Account.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceContact_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceContact_to_json"
}

module InstanceIcon = {
  type t = {
    size: string,
    src: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceIcon_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceIcon_to_json"
}

module InstanceRegistrations = {
  type t = {
    approval_required: bool,
    enabled: bool,
    message?: string,
    min_age?: int,
    reason_required?: bool,
    url?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceRegistrations_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceRegistrations_to_json"
}

module InstanceThumbnailVersions = {
  type t = {
    @as("@1x") _1x?: string,
    @as("@2x") _2x?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceThumbnailVersions_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceThumbnailVersions_to_json"
}

module InstanceThumbnail = {
  type t = {
    url: string,
    blurhash?: string,
    description?: string,
    versions?: InstanceThumbnailVersions.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceThumbnail_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceThumbnail_to_json"
}

module InstanceUsageUsers = {
  type t = {
    active_month: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceUsageUsers_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceUsageUsers_to_json"
}

module InstanceUsage = {
  type t = {
    users: InstanceUsageUsers.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instanceUsage_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instanceUsage_to_json"
}

module Instance = {
  type t = {
    configuration: InstanceConfiguration.t,
    contact: InstanceContact.t,
    description: string,
    domain: string,
    languages: array<string>,
    registrations: InstanceRegistrations.t,
    rules: array<Rule.t>,
    source_url: string,
    thumbnail: InstanceThumbnail.t,
    title: string,
    usage: InstanceUsage.t,
    version: string,
    api_versions?: InstanceApiVersions.t,
    icon?: array<InstanceIcon.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "instance_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "instance_to_json"
}

module ListRepliesPolicyEnum = {
  type t = string
}

module List = {
  type t = {
    exclusive: bool,
    id: string,
    replies_policy: ListRepliesPolicyEnum.t,
    title: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "list_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "list_to_json"
}

module Marker = {
  type t = {
    last_read_id: string,
    updated_at: string,
    version: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "marker_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "marker_to_json"
}

module NotificationFallback = {
  type t = {
    title: string,
    details?: string,
    summary?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "notificationFallback_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "notificationFallback_to_json"
}

module NotificationTypeEnum = {
  type t = string
}

module RelationshipSeveranceEventTypeEnum = {
  type t = string
}

module RelationshipSeveranceEvent = {
  type t = {
    created_at: string,
    followers_count: int,
    following_count: int,
    id: string,
    purged: bool,
    target_name: string,
    @as("type") type_: RelationshipSeveranceEventTypeEnum.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "relationshipSeveranceEvent_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "relationshipSeveranceEvent_to_json"
}

module Report = {
  type t = {
    action_taken: bool,
    category: ReportCategoryEnum.t,
    comment: string,
    created_at: string,
    forwarded: bool,
    id: string,
    target_account: Account.t,
    action_taken_at?: string,
    collection_ids?: array<string>,
    rule_ids?: array<string>,
    status_ids?: array<string>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "report_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "report_to_json"
}

module Notification = {
  type t = {
    account: Account.t,
    created_at: string,
    id: string,
    @as("type") type_: NotificationTypeEnum.t,
    event?: RelationshipSeveranceEvent.t,
    fallback?: NotificationFallback.t,
    group_key?: string,
    moderation_warning?: AccountWarning.t,
    report?: Report.t,
    status?: Status.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "notification_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "notification_to_json"
}

module NotificationPolicySummary = {
  type t = {
    pending_notifications_count: int,
    pending_requests_count: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "notificationPolicySummary_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "notificationPolicySummary_to_json"
}

module NotificationPolicy = {
  type t = {
    for_limited_accounts: string,
    for_new_accounts: string,
    for_not_followers: string,
    for_not_following: string,
    for_private_mentions: string,
    summary: NotificationPolicySummary.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "notificationPolicy_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "notificationPolicy_to_json"
}

module NotificationRequest = {
  type t = {
    account: Account.t,
    created_at: string,
    id: string,
    notifications_count: string,
    updated_at: string,
    last_status?: Status.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "notificationRequest_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "notificationRequest_to_json"
}

module PreferencesReadingExpandMediaEnum = {
  type t = string
}

module Preferences = {
  type t = {
    @as("posting:default:sensitive") posting_default_sensitive: bool,
    @as("posting:default:visibility") posting_default_visibility: StatusVisibilityEnum.t,
    @as("reading:expand:media") reading_expand_media: PreferencesReadingExpandMediaEnum.t,
    @as("reading:expand:spoilers") reading_expand_spoilers: bool,
    @as("posting:default:language") posting_default_language?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "preferences_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "preferences_to_json"
}

module TrendsLink = {
  type t = {
    description: string,
    embed_url: string,
    height: int,
    history: array<AdminEmailDomainBlockHistory.t>,
    html: string,
    provider_name: string,
    provider_url: string,
    title: string,
    @as("type") type_: TrendsLinkTypeEnum.t,
    url: string,
    width: int,
    author_name?: string,
    author_url?: string,
    authors?: array<PreviewCardAuthor.t>,
    blurhash?: string,
    image?: string,
    missing_attribution?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "trendsLink_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "trendsLink_to_json"
}

module PrivacyPolicy = {
  type t = {
    content: string,
    updated_at: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "privacyPolicy_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "privacyPolicy_to_json"
}

module Profile = {
  type t = {
    attribution_domains: array<string>,
    avatar_description: string,
    bot: bool,
    display_name: string,
    fields: array<Field.t>,
    header_description: string,
    id: string,
    indexable: bool,
    locked: bool,
    note: string,
    show_featured: bool,
    show_media: bool,
    show_media_replies: bool,
    avatar?: string,
    avatar_static?: string,
    discoverable?: bool,
    header?: string,
    header_static?: string,
    hide_collections?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "profile_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "profile_to_json"
}

module QuoteStateEnum = {
  type t = string
}

module Quote = {
  type t = {
    state: QuoteStateEnum.t,
    quoted_status?: Status.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "quote_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "quote_to_json"
}

module Relationship = {
  type t = {
    blocked_by: bool,
    blocking: bool,
    domain_blocking: bool,
    endorsed: bool,
    followed_by: bool,
    following: bool,
    id: string,
    muting: bool,
    muting_notifications: bool,
    note: string,
    notifying: bool,
    requested: bool,
    requested_by: bool,
    showing_reblogs: bool,
    languages?: array<string>,
    muting_expires_at?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "relationship_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "relationship_to_json"
}

module ScheduledStatusParamsPoll = {
  type t = {
    options: array<string>,
    expires_in: int,
    multiple: bool,
    hide_totals: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "scheduledStatusParamsPoll_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "scheduledStatusParamsPoll_to_json"
}

module ScheduledStatusParams = {
  type t = {
    application_id: int,
    text: string,
    visibility: StatusVisibilityEnum.t,
    with_rate_limit: bool,
    idempotency?: string,
    in_reply_to_id?: int,
    language?: string,
    media_ids?: array<string>,
    poll?: ScheduledStatusParamsPoll.t,
    scheduled_at?: string,
    sensitive?: bool,
    spoiler_text?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "scheduledStatusParams_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "scheduledStatusParams_to_json"
}

module ScheduledStatus = {
  type t = {
    id: string,
    media_attachments: array<MediaAttachment.t>,
    params: ScheduledStatusParams.t,
    scheduled_at: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "scheduledStatus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "scheduledStatus_to_json"
}

module TagHistory = {
  type t = {
    accounts: string,
    day: string,
    uses: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "tagHistory_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "tagHistory_to_json"
}

module Tag = {
  type t = {
    history: array<TagHistory.t>,
    name: string,
    url: string,
    featuring?: bool,
    following?: bool,
    id?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "tag_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "tag_to_json"
}

module Search = {
  type t = {
    accounts: array<Account.t>,
    hashtags: array<Tag.t>,
    statuses: array<Status.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "search_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "search_to_json"
}

module ShallowQuote = {
  type t = {
    state: QuoteStateEnum.t,
    quoted_status_id?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "shallowQuote_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "shallowQuote_to_json"
}

module TranslationPollOption = {
  type t = {
    title: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "translationPollOption_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "translationPollOption_to_json"
}

module StatusEditPoll = {
  type t = {
    options: array<TranslationPollOption.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "statusEditPoll_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "statusEditPoll_to_json"
}

module StatusEdit = {
  type t = {
    account: Account.t,
    content: string,
    created_at: string,
    emojis: array<CustomEmoji.t>,
    media_attachments: array<MediaAttachment.t>,
    sensitive: bool,
    spoiler_text: string,
    poll?: StatusEditPoll.t,
    quote?: JSON.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "statusEdit_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "statusEdit_to_json"
}

module StatusSource = {
  type t = {
    id: string,
    spoiler_text: string,
    text: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "statusSource_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "statusSource_to_json"
}

module Suggestion = {
  type t = {
    account: Account.t,
    sources?: array<string>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "suggestion_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "suggestion_to_json"
}

module AdminTag = {
  type t = {
    requires_review: bool,
    trendable: bool,
    usable: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "adminTag_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "adminTag_to_json"
}

module TermsOfService = {
  type t = {
    content: string,
    effective: bool,
    effective_date: string,
    succeeded_by?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "termsOfService_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "termsOfService_to_json"
}

module Token = {
  type t = {
    access_token: string,
    created_at: float,
    scope: string,
    token_type: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "token_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "token_to_json"
}

module TranslationAttachment = {
  type t = {
    description: string,
    id: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "translationAttachment_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "translationAttachment_to_json"
}

module TranslationPoll = {
  type t = {
    id: string,
    options: array<TranslationPollOption.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "translationPoll_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "translationPoll_to_json"
}

module Translation = {
  type t = {
    content: string,
    detected_source_language: string,
    language: string,
    media_attachments: array<TranslationAttachment.t>,
    provider: string,
    spoiler_text: string,
    poll?: TranslationPoll.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "translation_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "translation_to_json"
}

module V1Filter = {
  type t = {
    context: array<FilterContextEnum.t>,
    id: string,
    irreversible: bool,
    phrase: string,
    whole_word: bool,
    expires_at?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1Filter_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1Filter_to_json"
}

module V1InstanceConfigurationAccounts = {
  type t = {
    max_featured_tags: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1InstanceConfigurationAccounts_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1InstanceConfigurationAccounts_to_json"
}

module V1InstanceConfigurationMediaAttachments = {
  type t = {
    image_matrix_limit: int,
    image_size_limit: int,
    supported_mime_types: array<string>,
    video_frame_rate_limit: int,
    video_matrix_limit: int,
    video_size_limit: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1InstanceConfigurationMediaAttachments_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1InstanceConfigurationMediaAttachments_to_json"
}

module V1InstanceConfiguration = {
  type t = {
    accounts: V1InstanceConfigurationAccounts.t,
    media_attachments: V1InstanceConfigurationMediaAttachments.t,
    polls: InstanceConfigurationPolls.t,
    statuses: InstanceConfigurationStatuses.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1InstanceConfiguration_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1InstanceConfiguration_to_json"
}

module V1InstanceStats = {
  type t = {
    domain_count: int,
    status_count: int,
    user_count: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1InstanceStats_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1InstanceStats_to_json"
}

module V1InstanceUrls = {
  type t = {
    streaming_api: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1InstanceUrls_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1InstanceUrls_to_json"
}

module V1Instance = {
  type t = {
    approval_required: bool,
    configuration: V1InstanceConfiguration.t,
    description: string,
    email: string,
    invites_enabled: bool,
    languages: array<string>,
    registrations: bool,
    rules: array<Rule.t>,
    short_description: string,
    stats: V1InstanceStats.t,
    title: string,
    uri: string,
    urls: V1InstanceUrls.t,
    version: string,
    contact_account?: Account.t,
    thumbnail?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1Instance_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1Instance_to_json"
}

module V1NotificationPolicy = {
  type t = {
    filter_new_accounts: bool,
    filter_not_followers: bool,
    filter_not_following: bool,
    filter_private_mentions: bool,
    summary: NotificationPolicySummary.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "v1NotificationPolicy_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "v1NotificationPolicy_to_json"
}

module WebPushSubscriptionAlerts = {
  type t = {
    @as("admin.report") admin_report: bool,
    @as("admin.sign_up") admin_sign_up: bool,
    favourite: bool,
    follow: bool,
    follow_request: bool,
    mention: bool,
    poll: bool,
    reblog: bool,
    status: bool,
    update: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "webPushSubscriptionAlerts_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "webPushSubscriptionAlerts_to_json"
}

module WebPushSubscription = {
  type t = {
    alerts: WebPushSubscriptionAlerts.t,
    endpoint: string,
    id: string,
    server_key: string,
    standard?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "webPushSubscription_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "webPushSubscription_to_json"
}

module NotificationGroup = {
  type t = {
    group_key: string,
    most_recent_notification_id: int,
    notifications_count: int,
    sample_account_ids: array<string>,
    @as("type") type_: NotificationTypeEnum.t,
    event?: RelationshipSeveranceEvent.t,
    fallback?: NotificationFallback.t,
    latest_page_notification_at?: string,
    moderation_warning?: AccountWarning.t,
    page_max_id?: string,
    page_min_id?: string,
    report?: Report.t,
    status_id?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "notificationGroup_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "notificationGroup_to_json"
}

module GroupedNotificationsResults = {
  type t = {
    accounts: array<Account.t>,
    notification_groups: array<NotificationGroup.t>,
    statuses: array<Status.t>,
    partial_accounts?: array<PartialAccountWithAvatar.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "groupedNotificationsResults_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "groupedNotificationsResults_to_json"
}

module DiscoverOauthServerConfigurationResponse = {
  type t = {
    app_registration_endpoint: string,
    authorization_endpoint: string,
    code_challenge_methods_supported: array<string>,
    grant_types_supported: array<string>,
    issuer: string,
    response_modes_supported: array<string>,
    response_types_supported: array<string>,
    revocation_endpoint: string,
    scopes_supported: OAuthScopes.t,
    service_documentation: string,
    token_endpoint: string,
    token_endpoint_auth_methods_supported: array<string>,
    userinfo_endpoint: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "discoverOauthServerConfigurationResponse_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "discoverOauthServerConfigurationResponse_to_json"
}

module OEmbedResponse = {
  type t = {
    author_name: string,
    author_url: string,
    cache_age: int,
    html: string,
    provider_name: string,
    provider_url: string,
    title: string,
    @as("type") type_: string,
    version: string,
    width: int,
    height?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "oEmbedResponse_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "oEmbedResponse_to_json"
}

module ValidationError = {
  type t = {
    error: string,
    details: JSON.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "validationError_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "validationError_to_json"
}

module AsyncRefreshResponse = {
  type t = {
    async_refresh: AsyncRefresh.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "asyncRefreshResponse_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "asyncRefreshResponse_to_json"
}

module CustomError422ErrorDetailsName = {
  type t = {
    description: string,
    error: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "customError422ErrorDetailsName_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "customError422ErrorDetailsName_to_json"
}

module CustomError422ErrorDetails = {
  type t = {
    name: array<CustomError422ErrorDetailsName.t>,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "customError422ErrorDetails_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "customError422ErrorDetails_to_json"
}

module CustomError422Error = {
  type t = {
    details: CustomError422ErrorDetails.t,
    error: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "customError422Error_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "customError422Error_to_json"
}

module CustomError422 = {
  type t = {
    error: CustomError422Error.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "customError422_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "customError422_to_json"
}

module CountResponse = {
  type t = {
    count: int,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "countResponse_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "countResponse_to_json"
}

module MergedResponse = {
  type t = {
    merged: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "mergedResponse_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "mergedResponse_to_json"
}

module BaseStatus = {
  type t = {
    in_reply_to_id?: string,
    language?: string,
    quote_approval_policy?: string,
    quoted_status_id?: string,
    scheduled_at?: string,
    sensitive?: bool,
    spoiler_text?: string,
    visibility?: StatusVisibilityEnum.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "baseStatus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "baseStatus_to_json"
}

module TextStatus = {
  type t = {
    in_reply_to_id?: string,
    language?: string,
    quote_approval_policy?: string,
    quoted_status_id?: string,
    scheduled_at?: string,
    sensitive?: bool,
    spoiler_text?: string,
    visibility?: StatusVisibilityEnum.t,
    status: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "textStatus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "textStatus_to_json"
}

module MediaStatus = {
  type t = {
    in_reply_to_id?: string,
    language?: string,
    quote_approval_policy?: string,
    quoted_status_id?: string,
    scheduled_at?: string,
    sensitive?: bool,
    spoiler_text?: string,
    visibility?: StatusVisibilityEnum.t,
    media_ids: array<string>,
    status?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "mediaStatus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "mediaStatus_to_json"
}

module PollStatusPoll = {
  type t = {
    options?: array<string>,
    expires_in?: int,
    multiple?: bool,
    hide_totals?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "pollStatusPoll_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "pollStatusPoll_to_json"
}

module PollStatus = {
  type t = {
    in_reply_to_id?: string,
    language?: string,
    quote_approval_policy?: string,
    quoted_status_id?: string,
    scheduled_at?: string,
    sensitive?: bool,
    spoiler_text?: string,
    visibility?: StatusVisibilityEnum.t,
    poll: PollStatusPoll.t,
    status?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "pollStatus_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "pollStatus_to_json"
}

module PatchAccountsUpdateCredentialsSource = {
  type t = {
    privacy?: StatusVisibilityEnum.t,
    sensitive?: bool,
    language?: string,
    quote_policy?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "patchAccountsUpdateCredentialsSource_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "patchAccountsUpdateCredentialsSource_to_json"
}

module CreateFilterV2KeywordsAttributes = {
  type t = {
    keyword?: string,
    whole_word?: bool,
    id?: string,
    _destroy?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "createFilterV2KeywordsAttributes_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "createFilterV2KeywordsAttributes_to_json"
}

module GetInstanceActivityResponse = {
  type t = {
    week?: string,
    statuses?: string,
    logins?: string,
    registrations?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "getInstanceActivityResponse_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "getInstanceActivityResponse_to_json"
}

module CreateMarkerHome = {
  type t = {
    last_read_id?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "createMarkerHome_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "createMarkerHome_to_json"
}

module CreatePushSubscriptionSubscriptionKeys = {
  type t = {
    p256dh?: string,
    auth?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "createPushSubscriptionSubscriptionKeys_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "createPushSubscriptionSubscriptionKeys_to_json"
}

module CreatePushSubscriptionSubscription = {
  type t = {
    keys?: CreatePushSubscriptionSubscriptionKeys.t,
    endpoint?: string,
    standard?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "createPushSubscriptionSubscription_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "createPushSubscriptionSubscription_to_json"
}

module CreatePushSubscriptionDataAlerts = {
  type t = {
    mention?: bool,
    quote?: bool,
    status?: bool,
    reblog?: bool,
    follow?: bool,
    follow_request?: bool,
    favourite?: bool,
    poll?: bool,
    update?: bool,
    quoted_update?: bool,
    @as("admin.sign_up") admin_sign_up?: bool,
    @as("admin.report") admin_report?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "createPushSubscriptionDataAlerts_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "createPushSubscriptionDataAlerts_to_json"
}

module CreatePushSubscriptionData = {
  type t = {
    alerts?: CreatePushSubscriptionDataAlerts.t,
    policy?: string,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "createPushSubscriptionData_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "createPushSubscriptionData_to_json"
}

module PutPushSubscriptionDataAlerts = {
  type t = {
    mention?: bool,
    status?: bool,
    reblog?: bool,
    follow?: bool,
    follow_request?: bool,
    favourite?: bool,
    poll?: bool,
    update?: bool,
    @as("admin.sign_up") admin_sign_up?: bool,
    @as("admin.report") admin_report?: bool,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "putPushSubscriptionDataAlerts_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "putPushSubscriptionDataAlerts_to_json"
}

module PutPushSubscriptionData = {
  type t = {
    alerts?: PutPushSubscriptionDataAlerts.t,
  }
  @module("./melange-dist/ComponentSchemas.js") external of_json: JSON.t => t = "putPushSubscriptionData_of_json"
  @module("./melange-dist/ComponentSchemas.js") external to_json: t => JSON.t = "putPushSubscriptionData_to_json"
}

