// API endpoints (ReScript type layer).
// Generated by melange-jsdoc-gen. DO NOT EDIT.
// send delegates encode/decode to the Melange layer; inject fetch for transport.

type fetchFn = (string, string, JSON.t) => promise<JSON.t>

module AccountId = {
  module GetByAccountIdCollections = {
    type request = {
      account_id: string,
      limit?: int,
      offset?: int,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getByAccountIdCollections_send"
  }

  module GetByAccountIdInCollections = {
    type request = {
      account_id: string,
      limit?: int,
      offset?: int,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getByAccountIdInCollections_send"
  }

}

module Accounts = {
  module CreateAccount = {
    type request = {
      agreement: bool,
      email: string,
      locale: string,
      password: string,
      username: string,
      date_of_birth?: string,
      reason?: string,
    }
    type response = ComponentSchemas.Token.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createAccount_send"
  }

  module GetAccounts = {
    type request = {
      id?: array<string>,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccounts_send"
  }

  module GetAccount = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Account.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccount_send"
  }

  module PostAccountBlock = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountBlock_send"
  }

  module PostAccountEndorse = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountEndorse_send"
  }

  module GetAccountEndorsements = {
    type request = {
      id: string,
      limit?: int,
      max_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountEndorsements_send"
  }

  module GetAccountFeaturedTags = {
    type request = {
      id: string,
    }
    type response = array<ComponentSchemas.FeaturedTag.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountFeaturedTags_send"
  }

  module PostAccountFollow = {
    type request = {
      id: string,
      languages?: array<string>,
      notify?: bool,
      reblogs?: bool,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountFollow_send"
  }

  module GetAccountFollowers = {
    type request = {
      id: string,
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountFollowers_send"
  }

  module GetAccountFollowing = {
    type request = {
      id: string,
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountFollowing_send"
  }

  module GetAccountIdentityProofs = {
    type request = {
      id: string,
    }
    type response = array<ComponentSchemas.IdentityProof.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountIdentityProofs_send"
  }

  module GetAccountLists = {
    type request = {
      id: string,
    }
    type response = array<ComponentSchemas.List.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountLists_send"
  }

  module PostAccountMute = {
    type request = {
      id: string,
      duration?: int,
      notifications?: bool,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountMute_send"
  }

  module PostAccountNote = {
    type request = {
      id: string,
      comment?: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountNote_send"
  }

  module PostAccountPin = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountPin_send"
  }

  module PostAccountRemoveFromFollowers = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountRemoveFromFollowers_send"
  }

  module GetAccountStatuses = {
    type request = {
      id: string,
      exclude_reblogs?: bool,
      exclude_replies?: bool,
      limit?: int,
      max_id?: string,
      min_id?: string,
      only_media?: bool,
      pinned?: bool,
      since_id?: string,
      tagged?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountStatuses_send"
  }

  module PostAccountUnblock = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountUnblock_send"
  }

  module PostAccountUnendorse = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountUnendorse_send"
  }

  module PostAccountUnfollow = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountUnfollow_send"
  }

  module PostAccountUnmute = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountUnmute_send"
  }

  module PostAccountUnpin = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAccountUnpin_send"
  }

  module GetAccountsFamiliarFollowers = {
    type request = {
      id?: array<string>,
    }
    type response = array<ComponentSchemas.FamiliarFollowers.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountsFamiliarFollowers_send"
  }

  module GetAccountLookup = {
    type request = {
      acct: string,
    }
    type response = ComponentSchemas.Account.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountLookup_send"
  }

  module GetAccountRelationships = {
    type request = {
      id?: array<string>,
      with_suspended?: bool,
    }
    type response = array<ComponentSchemas.Relationship.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountRelationships_send"
  }

  module GetAccountSearch = {
    type request = {
      q: string,
      following?: bool,
      limit?: int,
      offset?: int,
      resolve?: bool,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountSearch_send"
  }

  module PatchAccountsUpdateCredentials = {
    type request = {
      attribution_domains?: array<string>,
      avatar?: string,
      bot?: bool,
      discoverable?: bool,
      display_name?: string,
      fields_attributes?: JSON.t,
      header?: string,
      hide_collections?: bool,
      indexable?: bool,
      locked?: bool,
      note?: string,
      source?: ComponentSchemas.PatchAccountsUpdateCredentialsSource.t,
    }
    type response = ComponentSchemas.CredentialAccount.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "patchAccountsUpdateCredentials_send"
  }

  module GetAccountsVerifyCredentials = {
    type request = unit
    type response = ComponentSchemas.CredentialAccount.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAccountsVerifyCredentials_send"
  }

}

module Announcements = {
  module GetAnnouncements = {
    type request = unit
    type response = array<ComponentSchemas.Announcement.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAnnouncements_send"
  }

  module PostAnnouncementDismiss = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAnnouncementDismiss_send"
  }

  module UpdateAnnouncementReaction = {
    type request = {
      id: string,
      name: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateAnnouncementReaction_send"
  }

  module DeleteAnnouncementReaction = {
    type request = {
      id: string,
      name: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteAnnouncementReaction_send"
  }

}

module AnnualReports = {
  module GetAnnualReports = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAnnualReports_send"
  }

  module GetAnnualReportsByYear = {
    type request = {
      year: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAnnualReportsByYear_send"
  }

  module PostAnnualReportGenerate = {
    type request = {
      year: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAnnualReportGenerate_send"
  }

  module PostAnnualReportRead = {
    type request = {
      year: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postAnnualReportRead_send"
  }

  module GetAnnualReportState = {
    type request = {
      year: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAnnualReportState_send"
  }

}

module Apps = {
  module CreateApp = {
    type request = {
      client_name: string,
      redirect_uris: array<string>,
      scopes?: string,
      website?: string,
    }
    type response = ComponentSchemas.CredentialApplication.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createApp_send"
  }

  module GetAppsVerifyCredentials = {
    type request = unit
    type response = ComponentSchemas.Application.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAppsVerifyCredentials_send"
  }

}

module AsyncRefreshes = {
  module GetAsyncRefreshV1Alpha = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.AsyncRefreshResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getAsyncRefreshV1Alpha_send"
  }

}

module Blocks = {
  module GetBlocks = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getBlocks_send"
  }

}

module Bookmarks = {
  module GetBookmarks = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getBookmarks_send"
  }

}

module Collections = {
  module CreateCollection = {
    type request = {
      name: string,
      account_ids?: string,
      description?: string,
      discoverable?: bool,
      language?: string,
      sensitive?: bool,
      tag_name?: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createCollection_send"
  }

  module PostCollectionItems = {
    type request = {
      collection_id: string,
      account_id?: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postCollectionItems_send"
  }

  module DeleteCollectionItem = {
    type request = {
      collection_id: string,
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteCollectionItem_send"
  }

  module PostCollectionsByCollectionIdItemsByIdRevoke = {
    type request = {
      collection_id: string,
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postCollectionsByCollectionIdItemsByIdRevoke_send"
  }

  module GetCollection = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.CollectionWithAccounts.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getCollection_send"
  }

  module UpdateCollection = {
    type request = {
      id: string,
      description?: string,
      discoverable?: bool,
      language?: string,
      name?: string,
      sensitive?: bool,
      tag_name?: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateCollection_send"
  }

  module DeleteCollection = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteCollection_send"
  }

}

module Conversations = {
  module GetConversations = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Conversation.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getConversations_send"
  }

  module DeleteConversation = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteConversation_send"
  }

  module PostConversationRead = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Conversation.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postConversationRead_send"
  }

}

module CustomEmojis = {
  module GetCustomEmojis = {
    type request = unit
    type response = array<ComponentSchemas.CustomEmoji.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getCustomEmojis_send"
  }

}

module Directory = {
  module GetDirectory = {
    type request = {
      limit?: int,
      local?: bool,
      offset?: int,
      order?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getDirectory_send"
  }

}

module DomainBlocks = {
  module GetDomainBlocks = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<string>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getDomainBlocks_send"
  }

  module CreateDomainBlock = {
    type request = {
      domain: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createDomainBlock_send"
  }

  module DeleteDomainBlocks = {
    type request = {
      domain: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteDomainBlocks_send"
  }

}

module Emails = {
  module CreateEmailConfirmations = {
    type request = {
      email?: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createEmailConfirmations_send"
  }

}

module Endorsements = {
  module GetEndorsements = {
    type request = {
      limit?: int,
      max_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getEndorsements_send"
  }

}

module Favourites = {
  module GetFavourites = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFavourites_send"
  }

}

module FeaturedTags = {
  module GetFeaturedTags = {
    type request = unit
    type response = array<ComponentSchemas.FeaturedTag.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFeaturedTags_send"
  }

  module CreateFeaturedTag = {
    type request = {
      name: string,
    }
    type response = ComponentSchemas.FeaturedTag.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createFeaturedTag_send"
  }

  module DeleteFeaturedTag = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteFeaturedTag_send"
  }

  module GetFeaturedTagSuggestions = {
    type request = unit
    type response = array<ComponentSchemas.Tag.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFeaturedTagSuggestions_send"
  }

}

module Filters = {
  module GetFilters = {
    type request = unit
    type response = ComponentSchemas.V1Filter.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFilters_send"
  }

  module CreateFilter = {
    type request = {
      context: array<ComponentSchemas.FilterContextEnum.t>,
      phrase: string,
      expires_in?: int,
      irreversible?: bool,
      whole_word?: bool,
    }
    type response = ComponentSchemas.V1Filter.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createFilter_send"
  }

  module GetFilter = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.V1Filter.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFilter_send"
  }

  module UpdateFilter = {
    type request = {
      id: string,
      context: array<ComponentSchemas.FilterContextEnum.t>,
      phrase: string,
      expires_in?: int,
      irreversible?: bool,
      whole_word?: bool,
    }
    type response = ComponentSchemas.V1Filter.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateFilter_send"
  }

  module DeleteFilter = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteFilter_send"
  }

  module GetFiltersV2 = {
    type request = unit
    type response = array<ComponentSchemas.Filter.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFiltersV2_send"
  }

  module CreateFilterV2 = {
    type request = {
      context: array<ComponentSchemas.FilterContextEnum.t>,
      title: string,
      expires_in?: int,
      filter_action?: string,
      keywords_attributes?: array<ComponentSchemas.CreateFilterV2KeywordsAttributes.t>,
    }
    type response = ComponentSchemas.Filter.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createFilterV2_send"
  }

  module GetFilterKeywordsV2 = {
    type request = {
      filter_id: string,
    }
    type response = array<ComponentSchemas.FilterKeyword.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFilterKeywordsV2_send"
  }

  module PostFilterKeywordsV2 = {
    type request = {
      filter_id: string,
      keyword: string,
      whole_word?: bool,
    }
    type response = ComponentSchemas.FilterKeyword.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postFilterKeywordsV2_send"
  }

  module GetFilterStatusesV2 = {
    type request = {
      filter_id: string,
    }
    type response = array<ComponentSchemas.FilterStatus.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFilterStatusesV2_send"
  }

  module PostFilterStatusesV2 = {
    type request = {
      filter_id: string,
      status_id: string,
    }
    type response = ComponentSchemas.FilterStatus.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postFilterStatusesV2_send"
  }

  module GetFilterV2 = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Filter.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFilterV2_send"
  }

  module UpdateFilterV2 = {
    type request = {
      id: string,
      context?: array<ComponentSchemas.FilterContextEnum.t>,
      expires_in?: int,
      filter_action?: string,
      keywords_attributes?: array<ComponentSchemas.CreateFilterV2KeywordsAttributes.t>,
      title?: string,
    }
    type response = ComponentSchemas.Filter.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateFilterV2_send"
  }

  module DeleteFilterV2 = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteFilterV2_send"
  }

  module GetFiltersKeywordsByIdV2 = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.FilterKeyword.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFiltersKeywordsByIdV2_send"
  }

  module UpdateFiltersKeywordsByIdV2 = {
    type request = {
      id: string,
      keyword: string,
      whole_word?: bool,
    }
    type response = ComponentSchemas.FilterKeyword.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateFiltersKeywordsByIdV2_send"
  }

  module DeleteFiltersKeywordsByIdV2 = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteFiltersKeywordsByIdV2_send"
  }

  module GetFiltersStatusesByIdV2 = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.FilterStatus.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFiltersStatusesByIdV2_send"
  }

  module DeleteFiltersStatusesByIdV2 = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.FilterStatus.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteFiltersStatusesByIdV2_send"
  }

}

module FollowRequests = {
  module GetFollowRequests = {
    type request = {
      limit?: int,
      max_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFollowRequests_send"
  }

  module PostFollowRequestAuthorize = {
    type request = {
      account_id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postFollowRequestAuthorize_send"
  }

  module PostFollowRequestReject = {
    type request = {
      account_id: string,
    }
    type response = ComponentSchemas.Relationship.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postFollowRequestReject_send"
  }

}

module FollowedTags = {
  module GetFollowedTags = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Tag.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getFollowedTags_send"
  }

}

module Health = {
  module GetHealth = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getHealth_send"
  }

}

module Instance = {
  module GetInstance = {
    type request = unit
    type response = ComponentSchemas.V1Instance.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstance_send"
  }

  module GetInstanceActivity = {
    type request = unit
    type response = array<ComponentSchemas.GetInstanceActivityResponse.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceActivity_send"
  }

  module GetInstanceDomainBlocks = {
    type request = unit
    type response = array<ComponentSchemas.DomainBlock.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceDomainBlocks_send"
  }

  module GetInstanceExtendedDescription = {
    type request = unit
    type response = ComponentSchemas.ExtendedDescription.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceExtendedDescription_send"
  }

  module GetInstancePeers = {
    type request = unit
    type response = array<string>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstancePeers_send"
  }

  module GetInstancePrivacyPolicy = {
    type request = unit
    type response = ComponentSchemas.PrivacyPolicy.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstancePrivacyPolicy_send"
  }

  module GetInstanceRules = {
    type request = unit
    type response = array<ComponentSchemas.Rule.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceRules_send"
  }

  module GetInstanceTermsOfService = {
    type request = unit
    type response = ComponentSchemas.TermsOfService.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceTermsOfService_send"
  }

  module GetInstanceTermsOfServiceByDate = {
    type request = {
      date: string,
    }
    type response = ComponentSchemas.TermsOfService.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceTermsOfServiceByDate_send"
  }

  module GetInstanceTranslationLanguages = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceTranslationLanguages_send"
  }

  module GetInstanceV2 = {
    type request = unit
    type response = ComponentSchemas.Instance.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getInstanceV2_send"
  }

}

module Lists = {
  module GetLists = {
    type request = unit
    type response = array<ComponentSchemas.List.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getLists_send"
  }

  module CreateList = {
    type request = {
      title: string,
      exclusive?: bool,
      replies_policy?: ComponentSchemas.ListRepliesPolicyEnum.t,
    }
    type response = ComponentSchemas.List.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createList_send"
  }

  module GetList = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.List.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getList_send"
  }

  module UpdateList = {
    type request = {
      id: string,
      title: string,
      exclusive?: bool,
      replies_policy?: ComponentSchemas.ListRepliesPolicyEnum.t,
    }
    type response = ComponentSchemas.List.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateList_send"
  }

  module DeleteList = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteList_send"
  }

  module GetListAccounts = {
    type request = {
      id: string,
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getListAccounts_send"
  }

  module PostListAccounts = {
    type request = {
      id: string,
      account_ids: array<string>,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postListAccounts_send"
  }

  module DeleteListAccounts = {
    type request = {
      id: string,
      account_ids: array<string>,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteListAccounts_send"
  }

}

module Markers = {
  module GetMarkers = {
    type request = {
      timeline?: array<ComponentSchemas.FilterContextEnum.t>,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getMarkers_send"
  }

  module CreateMarker = {
    type request = {
      home?: ComponentSchemas.CreateMarkerHome.t,
      notifications?: ComponentSchemas.CreateMarkerHome.t,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createMarker_send"
  }

}

module Media = {
  module CreateMedia = {
    type request = unit
    type response = ComponentSchemas.MediaAttachment.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createMedia_send"
  }

  module GetMedia = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.MediaAttachment.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getMedia_send"
  }

  module DeleteMedia = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteMedia_send"
  }

  module UpdateMedia = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.MediaAttachment.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateMedia_send"
  }

  module CreateMediaV2 = {
    type request = unit
    type response = ComponentSchemas.MediaAttachment.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createMediaV2_send"
  }

}

module Mutes = {
  module GetMutes = {
    type request = {
      limit?: int,
      max_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.MutedAccount.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getMutes_send"
  }

}

module Notifications = {
  module GetNotifications = {
    type request = {
      account_id?: string,
      exclude_types?: array<ComponentSchemas.NotificationTypeEnum.t>,
      include_filtered?: bool,
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
      supported_types?: array<string>,
      types?: array<ComponentSchemas.NotificationTypeEnum.t>,
    }
    type response = array<ComponentSchemas.Notification.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotifications_send"
  }

  module GetNotification = {
    type request = {
      id: string,
      supported_types?: array<string>,
    }
    type response = ComponentSchemas.Notification.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotification_send"
  }

  module PostNotificationDismiss = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postNotificationDismiss_send"
  }

  module CreateNotificationClear = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createNotificationClear_send"
  }

  module GetNotificationRequests = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.NotificationRequest.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationRequests_send"
  }

  module GetNotificationsRequestsById = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.NotificationRequest.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationsRequestsById_send"
  }

  module PostNotificationsRequestsByIdAccept = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postNotificationsRequestsByIdAccept_send"
  }

  module PostNotificationsRequestsByIdDismiss = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postNotificationsRequestsByIdDismiss_send"
  }

  module CreateNotificationsRequestsAccept = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createNotificationsRequestsAccept_send"
  }

  module CreateNotificationsRequestsDismiss = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createNotificationsRequestsDismiss_send"
  }

  module GetNotificationsRequestsMerged = {
    type request = unit
    type response = ComponentSchemas.MergedResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationsRequestsMerged_send"
  }

  module GetNotificationsUnreadCount = {
    type request = {
      account_id?: string,
      exclude_types?: array<string>,
      limit?: int,
      types?: array<string>,
    }
    type response = ComponentSchemas.CountResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationsUnreadCount_send"
  }

  module GetNotificationsV2 = {
    type request = {
      account_id?: string,
      exclude_types?: array<ComponentSchemas.NotificationTypeEnum.t>,
      expand_accounts?: string,
      grouped_types?: array<ComponentSchemas.NotificationTypeEnum.t>,
      include_filtered?: bool,
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
      supported_types?: array<string>,
      types?: array<ComponentSchemas.NotificationTypeEnum.t>,
    }
    type response = ComponentSchemas.GroupedNotificationsResults.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationsV2_send"
  }

  module GetNotificationsByGroupKeyV2 = {
    type request = {
      group_key: string,
      supported_types?: array<string>,
    }
    type response = ComponentSchemas.GroupedNotificationsResults.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationsByGroupKeyV2_send"
  }

  module GetNotificationAccountsV2 = {
    type request = {
      group_key: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationAccountsV2_send"
  }

  module PostNotificationDismissV2 = {
    type request = {
      group_key: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postNotificationDismissV2_send"
  }

  module GetNotificationPolicyV2 = {
    type request = unit
    type response = ComponentSchemas.NotificationPolicy.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationPolicyV2_send"
  }

  module PatchNotificationPolicyV2 = {
    type request = unit
    type response = ComponentSchemas.NotificationPolicy.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "patchNotificationPolicyV2_send"
  }

  module GetNotificationsUnreadCountV2 = {
    type request = {
      account_id?: string,
      exclude_types?: array<string>,
      grouped_types?: array<string>,
      limit?: int,
      types?: array<string>,
    }
    type response = ComponentSchemas.CountResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getNotificationsUnreadCountV2_send"
  }

}

module Oauth = {
  module GetOauthAuthorize = {
    type request = {
      client_id: string,
      redirect_uri: string,
      response_type: string,
      code_challenge?: string,
      code_challenge_method?: string,
      force_login?: bool,
      lang?: string,
      scope?: string,
      state?: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getOauthAuthorize_send"
  }

  module PostOauthRevoke = {
    type request = {
      client_id: string,
      client_secret: string,
      token: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postOauthRevoke_send"
  }

  module PostOauthToken = {
    type request = {
      client_id: string,
      client_secret: string,
      code: string,
      grant_type: string,
      redirect_uri: string,
      code_verifier?: string,
      scope?: string,
    }
    type response = ComponentSchemas.Token.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postOauthToken_send"
  }

  module GetOauthUserinfo = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getOauthUserinfo_send"
  }

}

module Oembed = {
  module GetOembed = {
    type request = {
      url: string,
      maxheight?: int,
      maxwidth?: int,
    }
    type response = ComponentSchemas.OEmbedResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getOembed_send"
  }

}

module Polls = {
  module GetPoll = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Poll.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getPoll_send"
  }

  module PostPollVotes = {
    type request = {
      id: string,
      choices: array<int>,
    }
    type response = ComponentSchemas.Poll.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postPollVotes_send"
  }

}

module Preferences = {
  module GetPreferences = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getPreferences_send"
  }

}

module Profile = {
  module GetProfile = {
    type request = unit
    type response = ComponentSchemas.Profile.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getProfile_send"
  }

  module PatchProfile = {
    type request = {
      attribution_domains?: array<string>,
      avatar?: string,
      avatar_description?: string,
      bot?: bool,
      discoverable?: bool,
      display_name?: string,
      fields_attributes?: JSON.t,
      header?: string,
      header_description?: string,
      hide_collections?: bool,
      indexable?: bool,
      locked?: bool,
      note?: string,
      show_featured?: bool,
      show_media?: bool,
      show_media_replies?: bool,
    }
    type response = ComponentSchemas.Profile.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "patchProfile_send"
  }

  module DeleteAvatar = {
    type request = unit
    type response = ComponentSchemas.CredentialAccount.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteAvatar_send"
  }

  module DeleteProfileHeader = {
    type request = unit
    type response = ComponentSchemas.CredentialAccount.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteProfileHeader_send"
  }

}

module Push = {
  module CreatePushSubscription = {
    type request = {
      subscription: ComponentSchemas.CreatePushSubscriptionSubscription.t,
      data?: ComponentSchemas.CreatePushSubscriptionData.t,
    }
    type response = ComponentSchemas.WebPushSubscription.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createPushSubscription_send"
  }

  module GetPushSubscription = {
    type request = unit
    type response = ComponentSchemas.WebPushSubscription.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getPushSubscription_send"
  }

  module PutPushSubscription = {
    type request = {
      data?: ComponentSchemas.PutPushSubscriptionData.t,
      policy?: string,
    }
    type response = ComponentSchemas.WebPushSubscription.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "putPushSubscription_send"
  }

  module DeletePushSubscription = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deletePushSubscription_send"
  }

}

module Reports = {
  module CreateReport = {
    type request = {
      account_id: string,
      category?: ComponentSchemas.ReportCategoryEnum.t,
      collection_ids?: array<string>,
      comment?: string,
      forward?: bool,
      rule_ids?: array<string>,
      status_ids?: array<string>,
    }
    type response = ComponentSchemas.Report.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createReport_send"
  }

}

module ScheduledStatuses = {
  module GetScheduledStatuses = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.ScheduledStatus.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getScheduledStatuses_send"
  }

  module GetScheduledStatus = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.ScheduledStatus.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getScheduledStatus_send"
  }

  module UpdateScheduledStatus = {
    type request = {
      id: string,
      scheduled_at?: string,
    }
    type response = ComponentSchemas.ScheduledStatus.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateScheduledStatus_send"
  }

  module DeleteScheduledStatus = {
    type request = {
      id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteScheduledStatus_send"
  }

}

module Search = {
  module GetSearchV2 = {
    type request = {
      q: string,
      account_id?: string,
      exclude_unreviewed?: bool,
      following?: bool,
      limit?: int,
      max_id?: string,
      min_id?: string,
      offset?: int,
      resolve?: bool,
      @as("type") type_?: string,
    }
    type response = ComponentSchemas.Search.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getSearchV2_send"
  }

}

module Statuses = {
  module CreateStatus = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "createStatus_send"
  }

  module GetStatuses = {
    type request = {
      id?: array<string>,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatuses_send"
  }

  module GetStatus = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatus_send"
  }

  module DeleteStatus = {
    type request = {
      id: string,
      delete_media?: bool,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteStatus_send"
  }

  module UpdateStatus = {
    type request = {
      id: string,
      language?: string,
      @as("media_attributes[]") media_attributes__?: array<string>,
      media_ids?: array<string>,
      poll?: ComponentSchemas.PollStatusPoll.t,
      quote_approval_policy?: string,
      sensitive?: bool,
      spoiler_text?: string,
      status?: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateStatus_send"
  }

  module PostStatusBookmark = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusBookmark_send"
  }

  module GetStatusContext = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Context.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatusContext_send"
  }

  module PostStatusFavourite = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusFavourite_send"
  }

  module GetStatusFavouritedBy = {
    type request = {
      id: string,
      limit?: int,
      max_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatusFavouritedBy_send"
  }

  module GetStatusHistory = {
    type request = {
      id: string,
    }
    type response = array<ComponentSchemas.StatusEdit.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatusHistory_send"
  }

  module UpdateStatusInteractionPolicy = {
    type request = {
      id: string,
      quote_approval_policy?: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "updateStatusInteractionPolicy_send"
  }

  module PostStatusMute = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusMute_send"
  }

  module PostStatusPin = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusPin_send"
  }

  module GetStatusQuotes = {
    type request = {
      id: string,
      limit?: int,
      max_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatusQuotes_send"
  }

  module PostStatusesByIdQuotesByQuotingStatusIdRevoke = {
    type request = {
      id: string,
      quoting_status_id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusesByIdQuotesByQuotingStatusIdRevoke_send"
  }

  module PostStatusReblog = {
    type request = {
      id: string,
      visibility?: ComponentSchemas.StatusVisibilityEnum.t,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusReblog_send"
  }

  module GetStatusRebloggedBy = {
    type request = {
      id: string,
      limit?: int,
      max_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatusRebloggedBy_send"
  }

  module GetStatusSource = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.StatusSource.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStatusSource_send"
  }

  module PostStatusTranslate = {
    type request = {
      id: string,
      lang?: string,
    }
    type response = ComponentSchemas.Translation.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusTranslate_send"
  }

  module PostStatusUnbookmark = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusUnbookmark_send"
  }

  module PostStatusUnfavourite = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusUnfavourite_send"
  }

  module PostStatusUnmute = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusUnmute_send"
  }

  module PostStatusUnpin = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusUnpin_send"
  }

  module PostStatusUnreblog = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Status.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postStatusUnreblog_send"
  }

}

module Streaming = {
  module GetStreamingDirect = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingDirect_send"
  }

  module GetStreamingHashtag = {
    type request = {
      tag: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingHashtag_send"
  }

  module GetStreamingHashtagLocal = {
    type request = {
      tag: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingHashtagLocal_send"
  }

  module GetStreamingHealth = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingHealth_send"
  }

  module GetStreamingList = {
    type request = {
      list: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingList_send"
  }

  module GetStreamingPublic = {
    type request = {
      only_media?: bool,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingPublic_send"
  }

  module GetStreamingPublicLocal = {
    type request = {
      only_media?: bool,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingPublicLocal_send"
  }

  module GetStreamingPublicRemote = {
    type request = {
      only_media?: bool,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingPublicRemote_send"
  }

  module GetStreamingUser = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingUser_send"
  }

  module GetStreamingUserNotification = {
    type request = unit
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getStreamingUserNotification_send"
  }

}

module Suggestions = {
  module GetSuggestions = {
    type request = {
      limit?: int,
    }
    type response = array<ComponentSchemas.Account.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getSuggestions_send"
  }

  module DeleteSuggestionsByAccountId = {
    type request = {
      account_id: string,
    }
    type response = JSON.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "deleteSuggestionsByAccountId_send"
  }

  module GetSuggestionsV2 = {
    type request = {
      limit?: int,
    }
    type response = array<ComponentSchemas.Suggestion.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getSuggestionsV2_send"
  }

}

module Tags = {
  module PostTagFeature = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Tag.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postTagFeature_send"
  }

  module PostTagUnfeature = {
    type request = {
      id: string,
    }
    type response = ComponentSchemas.Tag.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postTagUnfeature_send"
  }

  module GetTagsByName = {
    type request = {
      name: string,
    }
    type response = ComponentSchemas.Tag.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTagsByName_send"
  }

  module PostTagFollow = {
    type request = {
      name: string,
    }
    type response = ComponentSchemas.Tag.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postTagFollow_send"
  }

  module PostTagUnfollow = {
    type request = {
      name: string,
    }
    type response = ComponentSchemas.Tag.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "postTagUnfollow_send"
  }

}

module Timelines = {
  module GetTimelineDirect = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTimelineDirect_send"
  }

  module GetTimelineHome = {
    type request = {
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTimelineHome_send"
  }

  module GetTimelineLink = {
    type request = {
      url: string,
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTimelineLink_send"
  }

  module GetTimelinesListByListId = {
    type request = {
      list_id: string,
      limit?: int,
      max_id?: string,
      min_id?: string,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTimelinesListByListId_send"
  }

  module GetTimelinePublic = {
    type request = {
      limit?: int,
      local?: bool,
      max_id?: string,
      min_id?: string,
      only_media?: bool,
      remote?: bool,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTimelinePublic_send"
  }

  module GetTimelinesTagByHashtag = {
    type request = {
      hashtag: string,
      all?: array<string>,
      any?: array<string>,
      limit?: int,
      local?: bool,
      max_id?: string,
      min_id?: string,
      none?: array<string>,
      only_media?: bool,
      remote?: bool,
      since_id?: string,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTimelinesTagByHashtag_send"
  }

}

module Trends = {
  module GetTrendLinks = {
    type request = {
      limit?: int,
      offset?: int,
    }
    type response = array<ComponentSchemas.TrendsLink.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTrendLinks_send"
  }

  module GetTrendStatuses = {
    type request = {
      limit?: int,
      offset?: int,
    }
    type response = array<ComponentSchemas.Status.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTrendStatuses_send"
  }

  module GetTrendTags = {
    type request = {
      limit?: int,
      offset?: int,
    }
    type response = array<ComponentSchemas.Tag.t>
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getTrendTags_send"
  }

}

module WellKnown = {
  module GetWellKnownOauthAuthorizationServer = {
    type request = unit
    type response = ComponentSchemas.DiscoverOauthServerConfigurationResponse.t
    @module("./melange-dist/Endpoints.js") external send: (fetchFn, request) => promise<response> = "getWellKnownOauthAuthorizationServer_send"
  }

}

